### ISSUE TITLE
Weird late ADDON-Binder issue

### ISSUE THREAD

**Issue by Lisias** [net-lisias-ksp/TweakScale#10]
When loading a Part with TweakScale support, a strange double ADDON-BINDER log message happens. Theoretically, this should not happen.

This was confirmed to happen with only TweakScale installed, so it is one of the triggers.

### [Step 1](https://forum.kerbalspaceprogram.com/index.php?/topic/179030-141151-tweakscale-under-new-management-2018-1127/&do=findComment&comment=3485098)

Where I thought TweakScale would no be involved:

> On the line 163, "CallUpdaters" is inside a TryCatch that logs an Exception on exceptions. CallUdaters calls updateTestFlight , the one what could be doing such a mess. So, if this code were being triggering an exception, we would had a log on it.

> CallUpdaters is also called from OnTweakScaleChanged, that it's called on lines 343 and 732. No TryCatch on these calls, so a Stack Dump would happen for sure on your kSP log.

> The absence of such entries on my log suggests that's WeakScale is not directly involved on the mess.

### [Step 2](
https://forum.kerbalspaceprogram.com/index.php?/topic/179030-141151-tweakscale-under-new-management-2018-1127/&do=findComment&comment=3485177)

The logs from Speadge's KSP.log

```
[ERR 01:32:32.344] ADDON BINDER: Cannot resolve assembly: TestFlightCore, Culture=neutral, PublicKeyToken=null

[ERR 01:32:32.353] ADDON BINDER: Cannot resolve assembly: TestFlightCore, Culture=neutral, PublicKeyToken=null
```

### [Step 3](https://forum.kerbalspaceprogram.com/index.php?/topic/179030-141151-tweakscale-under-new-management-2018-1127/&page=6&tab=comments#comment-3488740)

Where I confirm the behaviour:

```
[LOG 00:43:35.732] PartLoader: Compiling Part 'AviationLights/Parts/lights/lightstrobe_white/lightstrobe_white'
[LOG 00:43:35.812] PartLoader: Part 'AviationLights/Parts/lights/lightstrobe_white/lightstrobe_white' has no database record. Creating.
[LOG 00:43:35.821] DragCubeSystem: Creating drag cubes for part 'lightstrobe.white'
[LOG 00:43:35.881] PartLoader: Compiling Part 'B9_Aerospace/Parts/Adapter_C125/Adapter_C125/B9_Adapter_C125'
[ERR 00:43:36.013] ADDON BINDER: Cannot resolve assembly: TestFlightCore, Culture=neutral, PublicKeyToken=null

[ERR 00:43:36.013] ADDON BINDER: Cannot resolve assembly: TestFlightCore, Culture=neutral, PublicKeyToken=null

[LOG 00:43:36.065] PartLoader: Part 'B9_Aerospace/Parts/Adapter_C125/Adapter_C125/B9_Adapter_C125' has no database record. Creating.
[LOG 00:43:36.073] DragCubeSystem: Creating drag cubes for part 'B9.Adapter.C125'
[LOG 00:43:36.136] PartLoader: Compiling Part 'B9_Aerospace/Parts/Adapter_M1/Adapter_SM1/B9_Adapter_SM1'
```
> And this appears to be happening on PartLoading, so, yeah, it's plausible that TweakScale would being fooled into believing that TestFlightCore is installed - but I think that TweakScale is trying to use someone else that have this hard dependency. TweakScale only tries to use TestFlightCore if it find that Interface on the system.

> And again, I don't see how one of these two statements:

```
tfInterface = Type.GetType("TestFlightCore.TestFlightInterface, TestFlightCore", false);

bool valueAdded = (bool)tfInterface.InvokeMember("AddInteropValue", BindingFlags.InvokeMethod | BindingFlags.Public | BindingFlags.Static, null, null, new System.Object[] { part, name, value, owner });
```
 > would trigger a "[ADDON BINDER]" error event (unless this is not an error, but a warning misnamed). TweakScale is dealing with Refl﻿ec﻿tion, would this code being run, the message would be about "method not found", 'invalid call" or something like this.

[MS Doc Link 1](https://docs.microsoft.com/en-us/dotnet/api/system.type.gettype?view=netframework-3.5#System_Type_GetType_System_String_System_Boolean_), [MS Doc Link 2](https://docs.microsoft.com/en-us/dotnet/api/system.type.invokemember?view=netframework-3.5), 

### [Step 4](https://forum.kerbalspaceprogram.com/index.php?/topic/179030-141151-tweakscale-under-new-management-2018-1127/&do=findComment&comment=348650)

Full log from the guy.
[KSP.log](https://github.com/net-lisias-ksp/TweakScale/files/2591965/KSP.log)

### [Step 5](
https://forum.kerbalspaceprogram.com/index.php?/topic/179030-141151-tweakscale-under-new-management-2018-1127/&do=findComment&comment=3488740)

Some considerations of mine:

>10 milliseconds is barely the minimum time the Thread.sleep can delay a thread on Windows, AFAIK.

> On a C++ it's a huge time lapse. On CSharp, not that much.

> Since this code is run on the "OnLoad" event of a Part, and since This happens by merely installing TweakScale on a plain vanilla installment, that would imply that KSP load Parts in more than one thread - so we would have concurrency. The variable that controls the presence of that interface is a static one - so the value is the same for every Part that instantiates this code - so, se second part would trigger the same code before the first part had time to reach that code. By the time the third (concurrent or not) part loading reaches this code, by some reason this would not happen anymore. 

> But all the evidences I have says that parts are loaded sequentially in a single thread on KSP load time. More interestingly, on my machine both logs happens at the exact same time:

```
[ERR 18:53:24.524] ADDON BINDER: Cannot resolve assembly: TestFlightCore, Culture=neutral, PublicKeyToken=null

[ERR 18:53:24.524] ADDON BINDER: Cannot resolve assembly: TestFlightCore, Culture=neutral, PublicKeyToken=null
```

> And there're a huge time between loading two parts on the same machine (on the same run I extracted the previous log):

```
[LOG 18:53:04.877] PartLoader: Compiling Part 'AirplanePlus/Parts/Aero/fixedwings/modelwarhawkfin/warhawkfin'
[LOG 18:53:04.906] PartLoader: Part 'AirplanePlus/Parts/Aero/fixedwings/modelwarhawkfin/warhawkfin' has no database record. Creating.
[LOG 18:53:04.912] DragCubeSystem: Creating drag cubes for part 'warhawkfin'
[LOG 18:53:05.090] PartLoader: Compiling Part 'AirplanePlus/Parts/Aero/flaps/doublefowlerflap/doublefowlerflap'
```

> See that it takes at least 30 milliseconds between the "compiling part" and "no database record".

> My guess is that this entry ("ADDON BINDER") is being issued two times on the same occurrence on the first run, and then being suppressed on the second and beyound. Your time can had happened by switching context between KSP and some other background process on your machine on a tight memory constrained box. But… This is a guess too.

**Comment by Lisias** [comment]
I marked this as "wontfix" because apparently this is harmless, and also out of my reach to be fixable (appears to be something on KSP itself).

**Comment by Lisias** [comment]
One year later. :)

When I wrote my own AppDomain [AssemblyResolver](https://github.com/net-lisias-ksp/KSPAPIExtensions/commit/4087c9104dfcc44a5bc51a22e959d68ad8c2551b) on KSPe, I came to terms that KSP's one is less than ideal. It's not exactly wrong, it's just not right neither: it complains about errors by just checking if an Assembly is loaded when not - and this is pretty confusing.

in a way or another, this is not a bug - not to mention a bug on TweakScale. So I'm closing it.

**Comment by 7ranceaddic7** [comment]
I get these with the KSPe.<insert version>.dll

**Comment by Lisias** [comment]
> I get these with the KSPe..dll

It's because I didn't managed to get rid of the Squad's "less than adequate" AssemblyResolver yet.

I need to find the name of the callback they used, so I could withdraw it from the Resolver pool, replacing it with mine instead (instead of just adding mine to the pool, and allowing their to run too), and then I would call it myself if needed (assuming I would not just replace it with something better written).

The whole problem is that the Stock AssemblyResolver doesn't differentiate a "It that Assembly Loaded?" question from "I need you to load this thing or I will die" request.

Developers that honor their jobs will always ask if something is loaded before using using it (when the thing is optional, see FlighttIntegrator) and if not found, they will deactivate the feature (obviously, when it's possible). 

It's what I'm doing now on KSPe.UI, by the way - I check for CTB, and if not found, rollback for the KSP 1.2 code where it's not a requirement. However, since I lost trust on the stock Resolver (not to mention this [kind of stuff I need to handle continuously](https://forum.kerbalspaceprogram.com/index.php?/topic/179030-ksp-141-tweakscale-under-lisias-management-24321-2020-00804/&do=findComment&comment=3485098)), I decided to check for the [DLL file instead](https://github.com/net-lisias-ksp/KSPAPIExtensions/blob/7d62e5e78caeed799480b2cc1d6def231cfe24ad/Source/KSPe.UI/Startup.cs#L40) taking advantage from LGG's habit of checking for the DLL place and complaining if it's somewhere else.
