### ISSUE TITLE
FATAL TweakScale Error 

### ISSUE THREAD

**Issue by Shima88** [net-lisias-ksp/TweakScale#104]
Good day. I got a FATAL TweakScale Error
[KSP.log](https://github.com/net-lisias-ksp/TweakScale/files/4564083/KSP.log)
![image](https://user-images.githubusercontent.com/64642653/80804728-9a8fa480-8be8-11ea-87e3-7be4af02ddb5.png)

**Comment by Lisias** [comment]
```
[LOG 13:32:20.294] Applying update TweakScale/patches/NF/NFS_TweakScale/@PART[solarpanel-blanket-1] to NearFutureSolar/Parts/Deprecated/solarpanel-blanket/solarpanel-blanket-1.cfg/PART[solarpanel-blanket-1]
...
[LOG 13:33:17.687] Applying update TweakScale/Deprecating/patches/NF/NFS_TweakScale/@PART[solarpanel-blanket-1]:FOR[TweakScale] to NearFutureSolar/Parts/Deprecated/solarpanel-blanket/solarpanel-blanket-1.cfg/PART[solarpanel-blanket-1]
```

Got it. You forgot to delete TweakScale folder's content before updating.

Since there's no user configuration stored on the GameData/TweakScale , it's safe (and safer) to always obliterate all older TweakScale artefacts before updating.

A lot of patches are going to be deprecated in the near future, so this should be standard procedure.

Cheers!

**Comment by Shima88** [comment]
> ```
> [LOG 13:32:20.294] Applying update TweakScale/patches/NF/NFS_TweakScale/@PART[solarpanel-blanket-1] to NearFutureSolar/Parts/Deprecated/solarpanel-blanket/solarpanel-blanket-1.cfg/PART[solarpanel-blanket-1]
> ...
> [LOG 13:33:17.687] Applying update TweakScale/Deprecating/patches/NF/NFS_TweakScale/@PART[solarpanel-blanket-1]:FOR[TweakScale] to NearFutureSolar/Parts/Deprecated/solarpanel-blanket/solarpanel-blanket-1.cfg/PART[solarpanel-blanket-1]
> ```
> 
> Got it. You forgot to delete TweakScale folder's content before updating.
> 
> Since there's no user configuration stored on the GameData/TweakScale , it's safe (and safer) to always obliterate all older TweakScale artefacts before updating.
> 
> A lot of patches are going to be deprecated in the near future, so this should be standard procedure.
> 
> Cheers!




> ```
> [LOG 13:32:20.294] Applying update TweakScale/patches/NF/NFS_TweakScale/@PART[solarpanel-blanket-1] to NearFutureSolar/Parts/Deprecated/solarpanel-blanket/solarpanel-blanket-1.cfg/PART[solarpanel-blanket-1]
> ...
> [LOG 13:33:17.687] Applying update TweakScale/Deprecating/patches/NF/NFS_TweakScale/@PART[solarpanel-blanket-1]:FOR[TweakScale] to NearFutureSolar/Parts/Deprecated/solarpanel-blanket/solarpanel-blanket-1.cfg/PART[solarpanel-blanket-1]
> ```
> 
> Got it. You forgot to delete TweakScale folder's content before updating.
> 
> Since there's no user configuration stored on the GameData/TweakScale , it's safe (and safer) to always obliterate all older TweakScale artefacts before updating.
> 
> A lot of patches are going to be deprecated in the near future, so this should be standard procedure.
> 
> Cheers!

Ok, thanks
