### ISSUE TITLE
New Sanity Check: duplicated properties #34 KIS mod

### ISSUE THREAD

**Issue by eraffenne74** [net-lisias-ksp/TweakScale#111]
Hello,
I installed the KIS mod and when I open KSP a message telling Tweakscale found 3 fatal errors. 
If anyone can help me 
Thanks
(KSP.log joined)
PS: Sorry for my english I'm french
[KSP.log](https://github.com/net-lisias-ksp/TweakScale/files/4677987/KSP.log)

**Comment by Lisias** [comment]
Hi,

Some patches are moving and being deprecated. You **need** to delete `GameData/TweakScale` before unzipping the new version on `GameData` .

It's a best practice to completely delete the previous TweakScale folder before applying a new version, to prevent leftovers from the previous installation to trigger the Sanity Checks as it happened to you.

Let me know if you need further assistance. I will keep this issue opened for a few days in the case you need more help.

Cheers!

**Comment by eraffenne74** [comment]
Hello lisias,
I replaced all the files of the tweakscale mod and no more "Houston we have a problem"
Thank you for your help :)!
