### ISSUE TITLE
KSP 1.8 (and 1.9) rendered the Sanity Checks useless.

### ISSUE THREAD

**Issue by Lisias** [net-lisias-ksp/TweakScale#114]
Something changed on KSP 1.8 that rendered the Sanity Checks plain useless.

I can't withdraw TweakScale anymore from a "insane" part.

Some other mechanism to deny TweakScale functions to insane parts are needed urgently.

![Screen Shot 2020-06-22 at 20 52 19](https://user-images.githubusercontent.com/64334/85345953-50c98900-b4ca-11ea-95cc-5a8800394219.png)

The **REALLY** nasty consequence from this stunt is that, once I implement the support for ModulePartVariants with mass, **ALL THE SAVEGAMES** with living crafts using these parts scaled **WILL BREAK**.

This is plain terrible. Lots and lots with parts are being created with this feature, **and all of them** are now at risk.

**Comment by 7ranceaddic7** [comment]
I ask this ignorantly and thinking out loud:

What is the manual workaround? Is there a manual workaround?

Is it possible to manually edit the Craft in the SaveFile to "get ahead of" implementing the support for ModulePartVariants with mass?

If manual editing is possible, is there a programmatic solution?

**Comment by Lisias** [comment]
> I ask this ignorantly and thinking out loud:

Brainstormings. Some of my best ideas came from things like that. Thanks for playing along!


> What is the manual workaround? Is there a manual workaround?

The manual workaround is to check the Log file, take every part mentioned and build a patch withdrawing TweakScale from the part by brute force, as I did on [this file](https://github.com/net-lisias-ksp/TweakScale/blob/master/Extras/TweakScale/Workarounds/VariantsWithMass.cfg).

Savvy users would be able to do it, common users definitively not.

 
> Is it possible to manually edit the Craft in the SaveFile to "get ahead of" implementing the support for ModulePartVariants with mass?

Interesting enough, craft files will probably pass scratchless (unless the user insist on trying to scale the part using an inconsistent UI). Once a fix is implemented, KSP will brute force the correct values on the craft at load.

The problem is the living crafts on the Universe, once they are instantiated and persisted on the savegame. KSP will brute force its way on that crafts too on savegame load, and so suddenly crafts will have some parts descaled or **correctly** scaled, and this will change the amount of resources and also the weight of the part, unbalancing it. Carefully crafted designs will fail for sure.


> If manual editing is possible, is there a programmatic solution?

A solution for the problem is already work in progress. In a way or another, I will deactivate TweakScale from that part.

The breakage that it will be caused by KSP brute forcing its way into living crafts, however, it'n unavoidable. There's no other alternative but to just take the hit. Again.

**Comment by Lisias** [comment]
How to Reproduce:

* Install TweakScale 2.4.3.14 .
* On the Editor, create something using the `Tube1` (T-12 Structural Tube). (see the image on the OP)
* Try to Scale this part.

By installing TweakScale 2.4.3.15 the problem was solved by brute force. See this [Commit](https://github.com/net-lisias-ksp/TweakScale/commit/2465deb2d2ae9415bdf187292ef7dda27b68a459) for details.
