### ISSUE TITLE
KSP 1.10.x Support Status

### ISSUE THREAD

**Issue by Lisias** [net-lisias-ksp/TweakScale#115]
# Status Report

## Update 2020-0729

Right now, TweakScale is under testing on KSP 1.10.1 . The current status for 1.10.1 is **UNKNOWN**.

- - -
- - -

Right now, TweakScale was tested on KSP 1.10 . Current status is **WORKS FINE** and it's now **supported**.

KSP Recall **is not needed** for sure on KSP 1.10 :)

But make backups of everything anyway. Just in case.

## Update 2020-0709 : 1630 Z

KSP 2.10 is **SUPPORTED**. Download the [latest TweakScale](https://github.com/net-lisias-ksp/TweakScale/releases) (currently 2.4.3.18). :)

- - -
- - -
- - -
- - -

## Update 2020-0704 : 1830 Z

KSP 1.10 revealed a hidden bug on TweakScale. Nothing serious, but it will potentially create lags on the Editor.

(on some circumstances, TweakScale inserts itself on the OnShipModified event cycle, but I forget to withdraw it from there, so once a part is deleted, TweakScale tries to handle dead parts and a lot of exceptions are thrown)

## Update 2020-0702 : 21:20 Z

TweakScale is working fine until the moment. Found no evidences of "old" parts misbehaving after TweakScaling them. That 9 parts with VARIANTS with MASS are still non scalable (as expected), but the good news is that no new parts were flagged with the problem (lack of support from TweakScale for parts with variants with mass).

KSP Recall definitively is not needed anymore (unless I find something new and write a fix on it).

## Update 2020-0701 : 18:00 Z

TweakScale appears to work fine. KSP Recall appears to be not needed. Still working on it.

**Comment by SkiRich** [comment]
Does this mean KSP Recall should be removed if not needed?  Is there an issue with leaving it installed?

**Comment by Lisias** [comment]
> Does this mean KSP Recall should be removed if not needed? Is there an issue with leaving it installed?

Yes. If not needed, it would only waste memory and CPU cycles.

**BUT** make backups from everything before trying it. It's possible that something still need it (perhaps improbable at this point, but why taking risks?)

**Comment by Lisias** [comment]
KSP Recall is not needed anymore. I spent some time playing 1.10 (without it) at lunch, and the Resources weren't reset at any time, on any situation. :)

**Comment by Jammer-TD** [comment]
I was sent here by your own warning message. so here is the test I did.
 It worked fine for me for a general build and test rocket flight, despite the warning.TS 2.4.3.15 v KSP1.10
post this test I removed KSPrecall with no errors or problems.
[ts2.4.3.15-1.10-01.zip](https://github.com/net-lisias-ksp/TweakScale/files/4871271/ts2.4.3.15-1.10-01.zip)
all the mods I used except USI MKS(select items within it, I was able to remove the issue items and use the rest for now).
Enjoy; I know I am.
Jammer-TD

**Comment by Lisias** [comment]
A bug on TweakScale that KSP 1.10 somehow unmasked was reported.

https://github.com/net-lisias-ksp/TweakScale/issues/119

**Comment by Lisias** [comment]
Reopening to check KSP 1.10.1

**Comment by Lisias** [comment]
Oukey, not exactly a surprise, but I don't wanna be caught with my pants down again.

```
[LOG 17:21:08.695] [TweakScale] TRACE: Checking Sanity for Tube1 at SquadExpansion/MakingHistory/Parts/Structural/Tube1/Tube1
[LOG 17:21:08.695] [TweakScale] ERROR: Part Tube1 (T-12 Structural Tube) didn't passed the sanity check due having a ModulePartVariants with
[LOG 17:21:08.695] [TweakScale] WARNING: Removing TweakScale support for Tube1 (T-12 Structural Tube).
[LOG 17:21:08.696] [TweakScale] TRACE: OnDestroy Tube1
```

KSP 1.10.1. are working as expected - no fatal problem detected, at least on a vanilla instalment.

So.. Yeah, TweakScale 2.4.3 supports 1.10.1. new release on the works
