### ISSUE TITLE
Wobble after loading.

### ISSUE THREAD

**Issue by Aberro** [net-lisias-ksp/TweakScale#118]
After loading savegame, solar panels placed onto scaled "M-Beam 200 I-Beam" begins to wobble intensely, until they all broke off.

**Comment by Lisias** [comment]
Well, it works for me. After going back to Main Menu and reloading, everything works fine on my rig:

![screenshot1](https://user-images.githubusercontent.com/64334/86510360-5a55c980-bdc5-11ea-83b4-de0083292412.png)

It's a constraint from the physics engine - your CPU is overloaded and not being able to fine tune the physics, what's end up in a series of "overshoots" while doing the calculations, that leads to the wobble.

Check if you are using autostruts. Deactivate them if you are - autostruts do help, but at a cost in CPU cycles and this can be a source of overshooting on the calculations. Perhaps the EAS-4 Strut would be a better choice.

Also, you can easy up things a bit for your CPU by setting the `Frame Limit` to 60. This will give more time each frame for the CPU do its work.

![Screen Shot 2020-07-04 at 06 49 48](https://user-images.githubusercontent.com/64334/86510449-04355600-bdc6-11ea-9159-6aa82d9f39eb.png)

If this is not enough, you will need to compromise, probably reducing the Add'On count on the game. You can also try a stunt that usually works, but makes the physics simulation less accurate: raise the `Max Physics Delta-Time Per frame` a bit. It's a trial and error, use the smaller value that does the trick to you:

![Screen Shot 2020-07-04 at 06 49 38](https://user-images.githubusercontent.com/64334/86510480-570f0d80-bdc6-11ea-8716-dca3873ba20e.png)

Let me know what worked for you, I will keep this issue open for some days.

**Comment by Aberro** [comment]
Uh, yes, this is unrelated to TweakScale. I've experienced same issue with unscaled beam. Thank you.
