### ISSUE TITLE
Support the new Parts introduced on KSP 1.10

### ISSUE THREAD

**Issue by Lisias** [net-lisias-ksp/TweakScale#120]
As the title says.

* Stock
  * Magnetometer (no  scaled)
  * MpoProbe https://github.com/net-lisias-ksp/TweakScale/commit/2595823c084d9824159961bb40547710d5daac8a
  * MtmStage https://github.com/net-lisias-ksp/TweakScale/commit/2595823c084d9824159961bb40547710d5daac8a
  * flagPartFlat https://github.com/net-lisias-ksp/TweakScale/commit/2595823c084d9824159961bb40547710d5daac8a
  * flagPartSize0 https://github.com/net-lisias-ksp/TweakScale/commit/2595823c084d9824159961bb40547710d5daac8a
  * flagPartSize1 https://github.com/net-lisias-ksp/TweakScale/commit/2595823c084d9824159961bb40547710d5daac8a
  * flagPartSize2 https://github.com/net-lisias-ksp/TweakScale/commit/2595823c084d9824159961bb40547710d5daac8a
  * flagPartSize3 https://github.com/net-lisias-ksp/TweakScale/commit/2595823c084d9824159961bb40547710d5daac8a
  * smallClaw https://github.com/net-lisias-ksp/TweakScale/commit/2595823c084d9824159961bb40547710d5daac8a
* Making History
  * flagPartSize1p5 https://github.com/net-lisias-ksp/TweakScale/commit/5a264016256971b21e5a73f496359dbb64c9a900
  * flagPartSize4 https://github.com/net-lisias-ksp/TweakScale/commit/5a264016256971b21e5a73f496359dbb64c9a900

**Comment by 7ranceaddic7** [comment]
I took a look at those parts.

The flag* do not need TS, there are meshes for small, medium, large, and huge.
TS is not applied to the sciency parts, so Magnetometer shouldn't either.

That leaves:
- MpoProbe
- MtmStage
- smallClaw

**Comment by Lisias** [comment]
Note to myself: PRs #122 & #123 already merged on the orthodox dev branch.

(so I don't check it - again - by the Nth time. :) )

**Comment by Lisias** [comment]
As I completely screwed my backlog on the past months (due Real Life being a Pain in the Ass™), KSP 1.12.0 ended up reaching the streets before I was ready for it.

Reworking the scheduling to rush the Patches revision.

**Comment by Lisias** [comment]
Implemented on commits https://github.com/net-lisias-ksp/TweakScale/commit/2595823c084d9824159961bb40547710d5daac8a and https://github.com/net-lisias-ksp/TweakScale/commit/5a264016256971b21e5a73f496359dbb64c9a900
