### ISSUE TITLE
Config getting skipped during creation.

### ISSUE THREAD

**Issue by 7ranceaddic7** [net-lisias-ksp/TweakScale#136]
Config in file 'C:\Games\Kerbal Space Program\KSP-1.9.1-JNSQ2\GameData\TweakScale\patches\Squad\Engines.legacy.cfg' contains an unnamed node. Skipping.

I'm at a loss.  ```Engines.legacy``` has the same format as ```Engines```, but damned if I can figureout whatsup.

(Also, is there an explainer somewhere on the other TweakScale thingys - TWEAKSCALEEXPONENTS, TWEAKSCALEBEHAVIOR, TWEAKSCALE* ... ?)

**Comment by Lisias** [comment]
Whoops... Missed this one. I'm downloading JNSQ to check.

**Comment by Lisias** [comment]
There's some documentation files on the [Docs](https://github.com/net-lisias-ksp/TweakScale/tree/dev/orthodox/GameData/TweakScale/Docs), but they are pretty minimalistic - the Forum's [TweakScale thread](https://forum.kerbalspaceprogram.com/index.php?/topic/179030-ksp-141-tweakscale-under-lisias-management-24321-2020-00804/page/67/&tab=comments#comment-3799651) has some insights, as well an [article](http://ksp.lisias.net/blogs/tech-support/TweakScale/How-to-write-a-patch/) on my site.

But everything are in need to be seriously proper documented. Check Issue #22 - now and then I do something and register there.

**Comment by Lisias** [comment]
ARGH!!! I misread the issue! =P

It's a problem on the tweakscale, not on tweakscale support on JNSQ :P

> I'm at a loss. Engines.legacy has the same format as Engines, but damned if I can figureout whatsup.

That makes two of us! o.O  Given the name of the file, you are using TS Beta (that's brave of you! :D ). That it's what I'm using on my day-to-day gaming. And...

```
[WRN 08:20:37.718] Config in file '/.users/lisias/Workspaces/KSP/runtime/1.10.0/GameData/TweakScale/patches/Squad/Engines.legacy.cfg' contains an unnamed node. Skipping.
```

Bingo. I completely missed this one. I'm trying to figure out what the hell is happening here.

**Comment by 7ranceaddic7** [comment]
I feel bad about bringing these things up and watching 2.4.4 getting pummeled.

**Comment by Lisias** [comment]
It's a minor issue, but it's an issue nevertheless.

I will have to deal with it sooner or later, so it's good to have it registered on the issue tracking so I don't forget it.

(and it's late Sunday, no more real development this week - don't hurt to spend a few hours on these issues)

**Comment by Lisias** [comment]
HA! You found a bad patch on TweakScale! 👍 

I forgot the `//` thingy on the comments on this one!

```
@PART[radialEngineMini]:FOR[TweakScale] for KSP <= 1.6.1
{
	#@TWEAKSCALEBEHAVIOR[Engine]/MODULE[TweakScale] { }
	%MODULE[TweakScale]
	{
		type = free
	}
}
```

Note to myself: I need to dig some time to extend the [lint tool](https://github.com/net-lisias-ksp/ksp-tools-public/issues/1) to understand MM patches.

**Comment by Lisias** [comment]
Fixed on commit: https://github.com/net-lisias-ksp/TweakScale/commit/c0b5c69a9c844c56133571921f8d09272806ad4a

**Comment by 7ranceaddic7** [comment]
> Note to myself: I need to dig some time to extend the lint tool to understand MM patches.

Oooh, I'm trying to teach myself Python right now.

Sporked.
