### ISSUE TITLE
Fatal error with 1.11 tweak scale

### ISSUE THREAD

**Issue by serp777** [net-lisias-ksp/TweakScale#146]
Hello,

I tried KSP 1.11 with the interstellar extended mod and got this error screen. Will there be a new release for tweak scale for 1.11 in the near future and what changes need to be made to support 1.11? I had to downgrade for the time being.

![image](https://user-images.githubusercontent.com/10540204/102571030-77453700-409d-11eb-9ff1-bf2717b7f6f5.png)

**Comment by Lisias** [comment]
Full KSP logs, or I can't help. Fatalities are usually related to double patching, and without the logs I can diagnose your problem.

And no, there will be no specific version for KSP 1.11. Assuming there's a problem on TweakScale (what's now impossible to diagnose without the KSP.log), a new release with **full** support for every KSP from 1.40 to 1.11 will be issued, as it always being done in the past.

**Comment by Lisias** [comment]
In time... If you updated TweakScale after installing KSPIE, keep in mind two things:

1) You need to completely REMOVE the old TweakScale folder before installing the new one. This is **standard** procedure for TweakScale, and you risk facing these FATALities when you don't clean up old files before installing new releases.

2) The KSPIE is being shipped with an older TweakScale version for a reason. Ask the KSPIE maintainer about the current status for using it on KSP 1.11 and TweakScale newer versions.

**Comment by Lisias** [comment]
It's not TweakScale. O just fired up 1.11.0 with a minimal set of mods (TweakScale, KAX, etc) and got this:

```
[LOG 08:47:18.390] [TweakScale] INFO: WriteDryCost Concluded : 546 parts found ; 0 checks failed ; 0 parts with hotfixes ; 0 parts with issues overruled ; 0 Show Stoppers found; 0 Sanity Check failed; 108 unscalable parts.
```

**Zero** Show Stoppers found.

So it's something wrong on your KSP installment. My best guess is that you didn't cleaned up TweakScale when you updated it.

**Comment by belgarion89** [comment]
Can confirm.  I was getting the same error after the patch, cleaned out my TweakScale install and re-installed, and now all is good.

**Comment by Lisias** [comment]
And now I confirm @belgarion89 confirmation. I cleanly installed the latest KSPIE on my testbed, and got **no** FATALities.

```
[LOG 16:05:14.967] [TweakScale] INFO: WriteDryCost Concluded : 994 parts found ; 0 checks failed ; 0 parts with hotfixes ; 0 parts with issues overruled ; 0 Show Stoppers found; 16 Sanity Check failed; 173 unscalable parts.
```

The 16 sanity checks are expected, as this TweakScale still don't know how to scale variants with mass and/or cost.

I will keep this opened for the weekend, im the case the user apply the KSP.log for further helping - but in a way or another, this is not related to TweakScale (neither is my fault! :D ).

**Comment by MrHuggy** [comment]
I'm having the same error report, tried several times it get it to work but none of them worked. Getting the same error in the logs about the GUI. Taking Tweakscale out and KSP runs without any problems.

Full Error Log > https://drive.google.com/file/d/1iPHTBb8n9O_6i9QX-cvNcjWuNCRKlbDz/view?usp=sharing

> [LOG 16:28:22.876] [TweakScale] Version 2.4.3.21 /L
> [ERR 16:28:22.890] Unable to use a named GUIStyle without a current skin. Most likely you need to move your GUIStyle initialization code to OnGUI
> 
> [ERR 16:28:22.892] Unable to use a named GUIStyle without a current skin. Most likely you need to move your GUIStyle initialization code to OnGUI
> 
> [LOG 16:28:22.895] [TweakScale] "Houston, we have a Problem!" about KSP 1.10.1 was displayed

**Comment by Lisias** [comment]
> https://drive.google.com/file/d/1iPHTBb8n9O_6i9QX-cvNcjWuNCRKlbDz/view?usp=sharing

Hi, sorry the late answer - but we are in a rush on the job.

I just checked your log, but unfortunately it's truncated! This is the last lines on it:

```
[LOG 16:47:11.965] Load(Audio): Chatterer/Sounds/chatter/expedition51/capcom/capcom_07
[LOG 16:47:11.983] Load(Audio): Chatterer/Sounds/chatter/expedition51/capcom/capcom_08
[LOG 16:47:12.012] Load(Audio): Chatterer/Sounds/chatter/expedition51/capcom/capcom_09
```

Way before the Sanity Checks executed on the Main Menu.

Please try again, but quit KSP before copying the KSP.log. The disk buffers on KSP are somewhat big (to enhance performance), but it also delays writings too much - and so you need to quit KSP (or open a game and play it for a while) in order to be sure the buffer is flushed into the disk, and so we can have a useable log!

**Comment by ttr** [comment]
Hey
Bit different but I think related
Reinstalled twekascale but still getting this warning - not sure if it's directly from Twakscale or some other mod is triggering this.
![image](https://user-images.githubusercontent.com/1327295/103137548-a4a76b80-46c1-11eb-842b-4e25d61f249b.png)
Mods installed from CKAN.
Logs, mod list and ckan export are under https://www.dropbox.com/sh/kob6jh2k8u50yyi/AADXfbc_g7OATfPyvj4kws7_a?dl=0

**Comment by MrHuggy** [comment]
Hi Lisias

Here is the full log that you wanted. https://drive.google.com/file/d/1C9XKLLWqfLTSxEFcNBo63n9haTxuya8Q/view?usp=sharing

I'm also getting some intermittent crashes, I don't know if they are related next time one happens I will have a look at the logs to see if they are or most likely not.

**Comment by Lisias** [comment]
> Reinstalled twekascale but still getting this warning - not sure if it's directly from Twakscale or some other mod is triggering this.

**Comment by Lisias** [comment]
Hi @ttr!

> Bit different but I think related
> Reinstalled twekascale but still getting this warning - not sure if it's directly from Twakscale or some other mod is triggering this.

yes, this is different, and this is harmless. What happened is that at the time I compiled TweakScale 2.4.3.21, I didn't had the slighest idea if KSP 1.11 would change something critical or not - and so I choose to err to the safe side.

Right now, after some tests, I detected no serious problems on KSP 1.11 that would affect TweakScale (and vice versa). So you can click Cancel and let the game run without problems.

I'm working on the next release of TweakScale, and it will not pesky you about KSP 1.11 anymore.

Cheers!

**Comment by Lisias** [comment]
Hi, @MrHuggy !

> Here is the full log that you wanted. https://drive.google.com/file/d/1C9XKLLWqfLTSxEFcNBo63n9haTxuya8Q/view?usp=sharing

Got it, but this log is fine - no fatalities!

```
[LOG 14:31:53.880] [TweakScale] INFO: WriteDryCost Concluded : 2160 parts found ; 0 checks failed ; 0 parts with hotfixes ; 0 parts with issues overruled ; 0 Show Stoppers found; 27 Sanity Check failed; 62 unscalable parts.
[LOG 14:31:53.947] [TweakScale] "TweakScale Warning" about sanity checks was displayed
```
The Sanity Checks are things that TweakScale does not knows how to handle yet, so it will be insane to allow TweakScale touch them. The next TweakScale release will handle most of them (but not all, there're still a few things to me implemented), so most of the current ones will vanish and you will be able to scale new parts soon.

These parts **never** was scalable before, so you don't need to worry about crafts and savegames - if it would be dangerous somehow, I would issue them as a FATAL, not in a Warning. :)


> I'm also getting some intermittent crashes, I don't know if they are related next time one happens I will have a look at the logs to see if they are or most likely not.

I have notice of crashes due a bug on Unity. Check this thread on Forum and see if it's similar somehow:

https://forum.kerbalspaceprogram.com/index.php?/topic/191081-tla_debug_stack_leak/

It's a bit complex, but all the historic of that bug is documented there, including how to know if it is bitting you. Ping me there if you need further assistance on the matter!

Cheers!

**Comment by Lisias** [comment]
In time, Merry Christmas, guys!

**Comment by MrHuggy** [comment]
> Hi, @MrHuggy !
> 
> > Here is the full log that you wanted. https://drive.google.com/file/d/1C9XKLLWqfLTSxEFcNBo63n9haTxuya8Q/view?usp=sharing
> 
> Got it, but this log is fine - no fatalities!
> 
> ```
> [LOG 14:31:53.880] [TweakScale] INFO: WriteDryCost Concluded : 2160 parts found ; 0 checks failed ; 0 parts with hotfixes ; 0 parts with issues overruled ; 0 Show Stoppers found; 27 Sanity Check failed; 62 unscalable parts.
> [LOG 14:31:53.947] [TweakScale] "TweakScale Warning" about sanity checks was displayed
> ```
> 
> The Sanity Checks are things that TweakScale does not knows how to handle yet, so it will be insane to allow TweakScale touch them. The next TweakScale release will handle most of them (but not all, there're still a few things to me implemented), so most of the current ones will vanish and you will be able to scale new parts soon.
> 
> These parts **never** was scalable before, so you don't need to worry about crafts and savegames - if it would be dangerous somehow, I would issue them as a FATAL, not in a Warning. :)
> 
> > I'm also getting some intermittent crashes, I don't know if they are related next time one happens I will have a look at the logs to see if they are or most likely not.
> 
> I have notice of crashes due a bug on Unity. Check this thread on Forum and see if it's similar somehow:
> 
> https://forum.kerbalspaceprogram.com/index.php?/topic/191081-tla_debug_stack_leak/
> 
> It's a bit complex, but all the historic of that bug is documented there, including how to know if it is bitting you. Ping me there if you need further assistance on the matter!
> 
> Cheers!

Thanks for your work Lisias, I haven't had any more issues so far.

**Comment by Lisias** [comment]
With KSP 2.4.4.0 on the wild, any further problems will probably be my fault, so I'm closing this one (as these are related to things not my fault! :) )
