### ISSUE TITLE
Not support KSP 1.110

### ISSUE THREAD

**Issue by siravijbb** [net-lisias-ksp/TweakScale#148]
![image](https://user-images.githubusercontent.com/47503079/102706212-73462e80-42c2-11eb-9096-4ad3eae48126.png)
Here still wait for new update of tweak scale

**Comment by Lisias** [comment]
You can hit Cancel and let it run, as I made tests on KSP 1.11 and until this moment no flaws were detected:

https://github.com/net-lisias-ksp/TweakScale/issues/147

A new release for TweakScale is currently Work In Progress, ETA 2 or 3 days.
