### ISSUE TITLE
Possible duplicated patches for "Nertea" in 2.4.4.0

### ISSUE THREAD

**Issue by chwthewke** [net-lisias-ksp/TweakScale#151]
Hi all,

Not having used TweakScale in a few years, I was learning about the sanity checks TweakScale does and in particular related to #34 as I'm getting a few FATAL errors related to that issue.

It seems that a duplicated set of patches found its way into the 2.4.4.0 release:

GameData/Deprecating/patches/Nertea.cfg
GameData/Deprecating/patches/Nerta.cfg

both exist and have (almost) identical content. I had deleted my previous installation, and also I checked that they are both in the 2.4.4.0 zip file.

Removing one of these files makes these FATAL errors (and the "Houston" popup in my case) go away

Happy holidays

**Comment by Lisias** [comment]
Jeez, you are right!

This file leaked somehow from the building sandbox, the file does not exists at all on the github - it was a failure on the building process.... 

I'm fixing it and will re-upload the file!

Thanks for the heads up!

**Comment by Lisias** [comment]
A new release was uploaded. Please download it!

https://github.com/net-lisias-ksp/TweakScale/releases/tag/RELEASE%2F2.4.4.0

**Comment by chwthewke** [comment]
I'm sorry to report that the issue seems to have crept back into 2.4.4.1 @Lisias

**Comment by Lisias** [comment]
> I'm sorry to report that the issue seems to have crept back into 2.4.4.1 @Lisias

Yeah, I know. I just released 2.4.4.2 with a (hopefully) definitive fix.

Sorry for that, I'm somewhat sleep deprived due a deadline that I had to meet today (don't ask - 2020 is just going to fight to the very end, as it appears!)
