### ISSUE TITLE
Missing or extra curly braces

### ISSUE THREAD

**Issue by AccidentalDisassembly** [net-lisias-ksp/TweakScale#157]
1. In the patch @PART[vernierEngine] inside GameData\TweakScale\patches\Squad\Control.cfg
2. In the commented-out patch @PART[InflatableAirlock] inside GameData\TweakScale\patches\SquadExpansion\MakingHistory\Coupling.cfg (just in case it were to be missed if/when un-commented!)

**Comment by Lisias** [comment]
The inflatableAirlock is on purpose, but the vernier caught with my pants down! Geez!

I'm fixing this before bed!

**Comment by Lisias** [comment]
On a side comment... I need to find time to implement MM patches on the [lint tool](https://github.com/net-lisias-ksp/ksp-tools-public). that would had prevented this.

**Comment by Lisias** [comment]
Fixed on commit https://github.com/net-lisias-ksp/TweakScale/commit/45ce330a02ff0b3a6cc4a4c5df476ecbc161d641
