### ISSUE TITLE
Duplicate TS patches in provided .cfgs

### ISSUE THREAD

**Issue by AccidentalDisassembly** [net-lisias-ksp/TweakScale#158]
These two patches...
1. GameData\TweakScale\patches\Squad\Control.cfg
2. GameData\TweakScale\patches\Squad\Pods.cfg 

... contain duplicate patches for "mk2DroneCore" and "probeCoreCube" - result: duplicate "type =" and/or " defaultScale = " properties on each part.

Note that this problem MAY (probably not, but MAYBE) only be apparent after fixing missing curly braces in other patches. That *seems* to have been the case for me, but I am not sure those two things are related in any way. In any case, the duplicate patches exist regardless.

**Comment by Lisias** [comment]
Another master bork of mine. Fixing it ASAP.

Thank you very much!

**Comment by Lisias** [comment]
Some more leftovers were found too.

Fixed on commit https://github.com/net-lisias-ksp/TweakScale/commit/769f1d256c3e8015a81a0918499f95d191dae725
