### ISSUE TITLE
Parachute scaling in symmetry

### ISSUE THREAD

**Issue by AccidentalDisassembly** [net-lisias-ksp/TweakScale#161]
Possibly related to issue 135, not sure.

Unusual behavior to report with parachutes, TweakScale, and symmetry. I discovered this in an install with Stage Recovery, but I don't *think* StageRecovery is causing it - it does reveal the problem in numerical form, though. I *think* this can be reproduced by the following steps (I am able to reproduce it consistently on an install with a number of mods used for testing, e.g. toolbar, EEX, TweakScale latest, I think, Firespitter dll, etc.):

1. In VAB, create craft, place decouplers in symmetry on the craft, place relatively heavy fuel tanks on the decouplers - I used rockomax jumbos. Using something heavy simply helps the problem become more obvious. Result: a rocket with boosters that will have parachutes on top for recovery, basically.
2. Place any parachute on the boosters, also in symmetry - open StageRecovery window to ensure that the single parachute will result in at least some reduction of reported fall speed, and/or some percent of recovery (either stat will reveal the issue).
3. With StageRecovery window still open, scale up the parachute any amount - the percent recovery and/or fall speed stats in the StageRecovery window will improve (slower fall or higher % recovery).
4. Click on the parachute to un-place it, then re-place it on one booster (Booster A) still in symmetry; it will be mirrored onto Booster B. Booster A (where the scaled-up parachute was placed) will report a new fall speed/recovery percent that is close to, but worse than, the stats reported in the SR window before picking the chute up and putting it back down.
5. Additionally, Booster B (the one onto which the parachute got mirrored by symmetry) will now report a much greater percent recovery / much slower fall speed.
6. Testing in flight after picking up and re-placing the tweakscaled parachutes, the booster parts with the chutes DO fall at the (different) speeds reported by StageRecovery - so I assume that StageRecovery is not causing the problem, but instead accurately reporting the new effects of the tweakscaled parts. Numbers reported by StageRecovery might be helpful somehow, maybe...

[Player.log](https://github.com/net-lisias-ksp/TweakScale/files/5876207/Player.log)

**Comment by Lisias** [comment]
It does not appear to be related to #135 , but something new.

I fired up a pretty minimal KSP 1.11.0 (**without** StageRecovery to rule out any side effect due it) and build the following craft:

![screenshot102](https://user-images.githubusercontent.com/64334/105984025-539be600-6078-11eb-85d4-4511d5c5cf64.png)

I placed the chute on the left tank, with **radial** symmetry, and then fired up the thing on a test drive:

![screenshot92](https://user-images.githubusercontent.com/64334/105981686-2437aa00-6075-11eb-91a6-c7f0972c5951.png)

![screenshot93](https://user-images.githubusercontent.com/64334/105981775-3ca7c480-6075-11eb-83b7-f95016a364c4.png)

As we can see, besides the craft being still balanced, the chutes are not providing drag equally (turned off the SAS to be sure). The left chute is giving me more drag than the right one.

This is remarkably similar to the tests I did on lilfting surfaces [here](https://github.com/net-lisias-ksp/TweakScale/issues/92#issuecomment-757426140):

![](https://user-images.githubusercontent.com/64334/104116178-063c1c80-52f5-11eb-8e57-e982626820e3.png)

So I redid the test using **MIRROR** symmetry:

![screenshot94](https://user-images.githubusercontent.com/64334/105981829-4e896780-6075-11eb-817e-25d0f2bc4120.png)

And yes, the same mibehaviour - this time the right chute is dragging more.

Interesting.

So I scaled down the side tanks to 1.25 and used **unscaled** chutes on the test.

![screenshot95](https://user-images.githubusercontent.com/64334/105981884-5cd78380-6075-11eb-98a0-f943e52a6d20.png)

![screenshot96](https://user-images.githubusercontent.com/64334/105981909-64972800-6075-11eb-9483-98e2ae02d33c.png)

**AND I GOT THE SAME MISBEHAVIOUR**. It's not TweakScale. It's the KSP physics engine.

To be absolutely sure about it, I removed TweakScale from the rig and tried again with a similar craft:

![screenshot98](https://user-images.githubusercontent.com/64334/105982000-7d074280-6075-11eb-9be8-f7a8e5587202.png)

![screenshot99](https://user-images.githubusercontent.com/64334/105982027-87294100-6075-11eb-961c-60f9e0f80e93.png)

![screenshot101](https://user-images.githubusercontent.com/64334/105982048-8e504f00-6075-11eb-97d2-8e8ddb5c1451.png)

["Ohh, that's a Bingo!!" :)](https://youtu.be/q5pESPQpXxE)

And this settle up the matter. It's KSP, not TweakScale! :)

**Comment by Lisias** [comment]
Being a KSP bug and not related to TweakScale, I'm closing this as "unrelated".

**Comment by Lisias** [comment]
For the sake of completude, I tested this behaviour on 

* KSP 1.7.3
* KSP 1.4.1
* KSP 1.3.1 (**without** TweakScale installed)

The behaviour is consistent on every test bed **BUT** 1.3.1, where the chutes DIDN`T tilted the craft.

Whatever is happening, was introduced probably on KSP 1.4.0 with the new Chute's Module
