### ISSUE TITLE
Issue with TweakScale install

### ISSUE THREAD

**Issue by 3mmen** [net-lisias-ksp/TweakScale#165]
When I installed TweakScale, somehow I made a new folder named GameData within the original GameData folder and extracted the TweakScale .zip files to the new folder. I then moved all of the TweakScale content of the new GameData folder into the orginal GameData folder and deleted the folder I accidentally made. 

After booting up KSP I got an error message saying there were 16 errors related to a file within the TweakScale mod. I also noticed that my atmospheric entry graphics were a little buggy, but the game and TweakScale mod seem to work just fine. 

What can I do to fix this issue? 
![Kerbal Space Program 1_30_2021 1_56_44 AM](https://user-images.githubusercontent.com/61128234/107163790-77650300-6979-11eb-94c6-a8067c88d983.png)
![Kerbal Space Program 1_30_2021 1_56_41 AM](https://user-images.githubusercontent.com/61128234/107163791-78963000-6979-11eb-8447-dc7979db72dc.png)
![Kerbal Space Program 2_6_2021 4_08_30 PM](https://user-images.githubusercontent.com/61128234/107163817-a54a4780-6979-11eb-9ea6-9a4c6166c156.png)

**Comment by Lisias** [comment]
You probably overwrote something you should not had when you moved all the GameData/GameData/* things back into GameData.

How many addons do you have installed? The best line of action is to delete everything and start from scratch.

In time, you don't need the Extras folder from TweakScale - unless somewhere in the past I told you to install something from there. They are optional patches to fix some specific situations that happened on the past.

Remove the Extras folder from your GameData. This should solve at least some of the problems.

But unless you are absolutely sure you didn't overwrote something you should not when you moved that files back to GameData, you may need to reinstall everything from scratch (including KSP itself).

And.. Yeah, I already ruined an KSP instalment doing exactly what you did. It was a test bed, so no real harm was done, but I inadvertently overwrite some files inside Squad folder... Keep backups of your savegames, just in case.

**Comment by 3mmen** [comment]
Well, if the problem is coming from a folder I don't need then I'll just delete the Extras folder. 
I don't think I overwrote something, if by overwrote you mean I replaced a duplicate file that was already in GameData. 

Honestly I think there should be an installer or something to make installing mods simpler. I really don't think having people go into the game's folder's is a good idea.

**Comment by Lisias** [comment]
If you are sure you didn't replace anything, then no real damage was done. Just get rid of the Extras.

(there's a INSTALL.md file with instructions, by the way).

About the installer, there's CKAN. If you are on CurseForge, they have an installer too. Somewhat minimalistic, but functional.

**Comment by 3mmen** [comment]
Forgot to say, I fixed the issue. I moved the SMI_AddOns.cfg file out of the KSP folder entirely. I think the issue was the SMI_AddOns.cfg file was trying to apply patches for a mod that I don't have. 

Thanks for the help and sorry for the late reply.

**Comment by TKS-Siege** [comment]
I just installed the mod as-is via Curse, and it is by default placing the mod in .\GameData\GameData\ which is resulting in a major error.

./GameData/Extras is also being created, and results in 16 errors of its own.

I have not installed any mods by any other facility other than CurseForge at this time, with the 1.11.1.x version of KSP. I have removed the mod - both manually and via Curse - and re-installed, and it goes right back to that path.

I was able to cut/paste the entire contents of that directory back into .\GameData\ and delete the .\GameData\Extras\ folder, then launch the game with no reported errors or other issues so far, however the mod is broken as far as Curse is concerned at this point, and I'm sure no longer being managed properly.

**Comment by Lisias** [comment]
> I just installed the mod as-is via Curse, and it is by default placing the mod in .\GameData\GameData\ which is resulting in a major error.

Now I understand from where came so much reports about GameData/GameData .... :(

I never installed anything using the CurseForge installer and, frankly, I don't see a reason why one should.

There's another problem on the Curse Installer - the file `999_Scale_Redist.dll` **must** be on the GameData folder, and on no other place. And the Curse Installer just refuses to install files on the GameData folder.

It's a Curse Installer limitation, and I can't do anything about.


> I was able to cut/paste the entire contents of that directory back into .\GameData\ and delete the .\GameData\Extras\ folder, then launch the game with no reported errors or other issues so far, however the mod is broken as far as Curse is concerned at this point, and I'm sure no longer being managed properly.

The installation process did by it is far from being ideal, and I don't see how I can overcome such limitations. The `999_Scale_Redist.dll` problem is real, this file need to be on GameData/ otherwise nothing will work properly due how KSP 1.8.0 do things on DLLs.

I will need to check if there's a way to mark the mod as Manual Install only. Or perhaps the installer has some option that I can use? It's ages since the last time I read that documentation....

**Comment by TKS-Siege** [comment]
Glad I could provide some clarification :)

**Comment by Lisias** [comment]
Changing from Support to Task/Enhancement, as this is something I need to work to make things right on Curseforge.

**Comment by Lisias** [comment]
Implemented on commit https://github.com/net-lisias-ksp/TweakScale/commit/3f086df51bb6e2c2e6ff05024adbbf3e80c90933 .

AFAIK, the `999_Scale_Redist.dll` will still persists, but at least is just one file and since this file is (virtually) never updated, once the user does it one time he is good for file (or until TweakScale3 is on the wild)

**Comment by Lisias** [comment]
I installed the CurseForge Installer for MacOS, and I didn't managed to make the damned thing to recognize my KSP installments.

All I got was this error message:

![Screen Shot 2021-02-22 at 19 34 42](https://user-images.githubusercontent.com/64334/108779157-3823de00-7545-11eb-8214-f67b88aee040.png)

I'm afraid I will have to publish the next Release of TweakScale hoping for the best, as I can't use this thing to test the package.

**Comment by Lisias** [comment]
I think I found the reason...

![Screen Shot 2021-02-22 at 19 40 08](https://user-images.githubusercontent.com/64334/108779641-ef205980-7545-11eb-8b18-019443f06e77.png)

Source: https://support.curseforge.com/en/support/solutions/articles/9000196615-curseforge-known-issues

**Comment by Lisias** [comment]
(hopefully - as I can't test it) fixed on commits https://github.com/net-lisias-ksp/TweakScale/commit/6659cf9258102b9647f7789321fbee20ddc463ca and https://github.com/net-lisias-ksp/TweakScale/commit/b2012e5ada4753aee1680da49dbc9496b230524b
