### ISSUE TITLE
TweakScale not installed on wrong directory

### ISSUE THREAD

**Issue by kolAflash** [net-lisias-ksp/TweakScale#209]
When starting KSP there's a message:

> Houston, we have a problem!
> 
> Unfortunately TweakScale is installed on the wrong directory!
> 
> It should be installed on /home/user/opt/Steam/steamapps/common/Kerbal Space Program/GameData/TweakScale/ but it's currently installed on /home/user/GamesStuff/KerbalSpaceProgram/GameData/TweakScale/ ! Delete the latter and be sure to install TweakScale on the former.
> [...]

`/home/user/GamesStuff/` is where I keep stuff like savegames, mods, ... for different games, so I can easily backup it.
And `/home/user/opt/Steam/steamapps/common/Kerbal Space Program/GameData/TweakScale/` is symlinked to `/home/user/GamesStuff/KerbalSpaceProgram/GameData/TweakScale/`, so it's actually in the right place.

&nbsp;

Maybe related:
https://github.com/net-lisias-ksp/KSPAPIExtensions/issues/6

**Comment by Lisias** [comment]
Closed by commit https://github.com/net-lisias-ksp/TweakScale/commit/075fd5b62920fe69453008b3812e6117762bc7f4
