### ISSUE TITLE
Small QoL suggestion, a thing that differs latest version from the previous ones

### ISSUE THREAD

**Issue by Alexsys** [net-lisias-ksp/TweakScale#217]
https://i.imgur.com/9WXTYcE.png

Back before the recent version, the Variants displayed didn't include all the options we have as tweakscale resizeable options, (the whole Variants spam seen in the picture).

The struggle comes not only with the fact that this is minimal information that is pretty much unnecessary, but it obstructs the most important thing in KSP ship building,
the Engine info,
If you try and scout for an engine with specific ISP for example, you must then right click and scroll down since its pushed down by the load of unnecessary Variants info,
before, you could just take a peek without scrolling down.

Finding the right engine for the mission / catching quick info about ISP of the engine became now a longer task.

we humans LOVE saving time as much as we can in minimal things, its part of man :)

we need the old window back for the soul of man, without the Variants of unnecessary obstructive information

**Comment by Lisias** [comment]
I agree. However, this is not on me - I didn't implemented a GetInfo call on TweakScale.

It's someone else doing this.

In fact, a GetInfo call **will** be implemented on the future, to allow easy spotting of parts that can be resized and to what scales (and I will consider this suggestion while implementing it), but right now there's none.

Assuming this is not something made by a 3rd Party Add'On, it's so a Stock feature - and so, I'm afraid you are out of luck, as I think it's unfeasible Squad would ever touch this issue.

But you can try suggesting this to KSPCommunityFixes.

**Comment by Lisias** [comment]
Being not an issue related to TweakScale, neither something that can be tackled down by it, I'm closing this.

But I will pinpoint this suggestion on the task for implementing the GetInfo - this issue gave me something to think about before implementing it.
