### ISSUE TITLE
.DDL files not loading or installed

### ISSUE THREAD

**Issue by Swords225** [net-lisias-ksp/TweakScale#224]
I've used your Tweakscale mod on KSP a lot and enjoy using it, in fact some of my creations won't be able to be used properly without it, apparently when I try to run the current version of KSP 1.12.2
![20211211155950_1](https://user-images.githubusercontent.com/95986549/145694144-1b20ff97-f292-491f-9834-3f16fd44c3d1.jpg)
 can you please figure out what the problem is so it can be corrected

**Comment by TheGroundedPilot** [comment]
@Lisias
same problem, I installed a bunch of mods
I removed the station Science mod, and it loaded that time
[KSP.log](https://github.com/net-lisias-ksp/TweakScale/files/7771966/KSP.log)

**Comment by Swords225** [comment]
here it is, sorry for not doing a tag on you

**Comment by Lisias** [comment]
> @Lisias

Hi! I took some days from coding (or even connecting to the Internet at all) due the holidays. Anyway, I'm back to business.

@TheGroundedPilot 

> same problem, I installed a bunch of mods
> I removed the station Science mod, and it loaded that time
> [KSP.log](https://github.com/net-lisias-ksp/TweakScale/files/7771966/KSP.log)

Yep. Found the problem:

````
[ERR 19:41:16.550] AssemblyLoader: Exception loading 'StationScience': System.Reflection.ReflectionTypeLoadException: Exception of type 'Sys
  at (wrapper managed-to-native) System.Reflection.Assembly.GetTypes(System.Reflection.Assembly,bool)
  at System.Reflection.Assembly.GetTypes () [0x00000] in <9577ac7a62ef43179789031239ba8798>:0
  at AssemblyLoader.LoadAssemblies () [0x000e6] in <39c0323fb6b449a4aaf3465c00ed3c8d>:0

Additional information about this exception:

 System.IO.FileNotFoundException: Could not load file or assembly 'KSPUtil, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' or one of
File name: 'KSPUtil, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
```

On a bitter remark, it was my understanding that KSP 1.12.3 would have fixed the DLL loading borkage. As it appears, it didn't. Oh, well..

Install KSPUtil (I don't know what it is), as it's a dependency for StationScience. You may need to contact StationScience maintainer for further information on the matter.

**Comment by Lisias** [comment]
@Swords225 :

> here it is, sorry for not doing a tag on you

Not a problem - but this time the delay was due the holidays (see previous comment).


> […](#)

Unfortunatelly, attaching files on email doesn't works… You need to drag and drop the file directly on a post here!

**Comment by Swords225** [comment]
@TheGroundedPilot <https://github.com/TheGroundedPilot> what station mod do
you use?

**Comment by Swords225** [comment]
@TheGroundedPilot <https://github.com/TheGroundedPilot> well what mods were
they that you had to remove, can you please tell me what they were so I can
make the same adjustments to mine?

**Comment by Lisias** [comment]
Hi, guys, there's something else in which I can help you on this issue? Otherwise I want to close it as it is clogging my backlog! 

Cheers, and happy new year!

**Comment by Swords225** [comment]
Thanks, you too!

**Comment by Lisias** [comment]
Well, case closed! :)
