### ISSUE TITLE
"KSPe.IO.Hierarchy`1" Issue

### ISSUE THREAD

**Issue by IkeFanboy64** [net-lisias-ksp/TweakScale#226]
This has already been brought up in prior reports, but I do want to bring it up as nothing I've tried so far has worked.

Every time I load up KSP, it reports the following show stopper problem.
![Capture](https://user-images.githubusercontent.com/92172758/147608107-249c966a-8ab1-4f55-8516-63b9c51f2794.PNG)

Whatever this glitch is, it seems to make Tweakscale unusable as entering the VAB and placing down the first part of the vessel causes it to glitch out, making you unable to pick up parts, attach parts, scale parts, start on a new vessel, or even exit the VAB. You can't even move the camera.

I am currently running the latest version on Tweakscale and Recall.

Since it's going to be needed to diagnose the problem, here's the log file. I did exit out of KSP shortly after recieving the error message, so if needed, I can send an updated log.

[KSP.log](https://github.com/net-lisias-ksp/TweakScale/files/7786385/KSP.log)

**Comment by IkeFanboy64** [comment]
UPDATE: Turns out ResearchBodies was causing the issue. I have uninstalled it and the error seems to be gone.

**Comment by Lisias** [comment]
@IkeFanboy64 whoops… I missed this one. (tag me with @Lisias , this will make github to notify me).

You had already diagnosed the problem, but this is what you need to do to in order to have Research Bodies working:

```
[ERR 14:20:28.052] ADDON BINDER: Cannot resolve assembly: ContractConfigurator, Culture=neutral, PublicKeyToken=null

[ERR 14:20:28.056] AssemblyLoader: Exception loading 'ResearchBodies': System.Reflection.ReflectionTypeLoadException: Exception of type 'System.Reflection.ReflectionTy
  at (wrapper managed-to-native) System.Reflection.Assembly.GetTypes(System.Reflection.Assembly,bool)
  at System.Reflection.Assembly.GetTypes () [0x00000] in <9577ac7a62ef43179789031239ba8798>:0
  at AssemblyLoader.LoadAssemblies () [0x000e6] in <39c0323fb6b449a4aaf3465c00ed3c8d>:0

Additional information about this exception:

 System.IO.FileNotFoundException: Could not load file or assembly 'ContractConfigurator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependenc
File name: 'ContractConfigurator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'

 System.IO.FileNotFoundException: Could not load file or assembly 'ContractConfigurator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependenc
File name: 'ContractConfigurator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
```

This piece of log is saying you need to install Contract Configurator in order to make ResearchBodies to work.

If another bork happens, it's probably because Contract Configurator also has a dependency, and the log will tell you what you need to install.

Cheers and happy new year!

**Comment by IkeFanboy64** [comment]
@Lisias Huge cheers, man. Thanks for helping me out here.

**Comment by Lisias** [comment]
Case closed! :)
