### ISSUE TITLE
Tweak Scale Did not find necessary DLL's error when loading the game

### ISSUE THREAD

**Issue by Radek-Bukowinski** [net-lisias-ksp/TweakScale#227]
![image](https://user-images.githubusercontent.com/74270526/148394423-4c8c1829-21ce-4cfa-aad2-d14210bb17fa.png)

This is what comes up after installing TweakScale through CKAN, with any combination of mods.

If I choose to load in the game, no parts can be clicked or rescaled, nor can the camera be moved.

**Comment by Lisias** [comment]
Hi, @Radek-Bukowinski !

please attache the **whole** KSP.log on a comment here, so I can inspect it and see what's happening.

Additionally, mention me using "@" (as I did to you now) so github will notify me and I can note it faster!

Cheers!

**Comment by Lisias** [comment]
Hi, @Radek-Bukowinski !!

This is still a problem for you?

**Comment by Drehverschluss** [comment]
Hello there, @Lisias 

I just have the same problem, i allready posted the error in ksp forums too but maby my logfile can help you too. Just tryed to make a new 1.12.3 modpack with all the "USI bleeding edge 1.12 stuff".
[KSP.log](https://github.com/net-lisias-ksp/TweakScale/files/7961016/KSP.log)

**Comment by Lisias** [comment]
@Drehverschluss ,

Well, it's not TweakScale:

```
<yada yada>
[LOG 19:22:14.352] Load(Assembly): /999_Scale_Redist
[LOG 19:22:14.352] AssemblyLoader: Loading assembly at D:\KerbalSpaceProgram Modding\KSP Backups\USIKolonization Modpack\Kerbal Space Program\GameData\999_Scale_Redist.dll
<yada yada yada>
[LOG 19:22:28.069] [KSPe.Light.TweakScale] Version 2.4.0.4 /L
[LOG 19:22:28.095] [TweakScale] Version 2.4.6.8 /L
[LOG 19:22:28.493] [TweakScale] ERROR: System.TypeInitializationException: The type initializer for 'KSPe.IO.Hierarchy`1' threw an exception. ---> System.Reflection.Reflec
```

Scale_Redist, KSPe.Light.TweakScale and Scale.dll are available - so everything appears to be set here.

Looking for Exceptions, I found this one:

```
[LOG 19:22:15.474] [AddonLoader]: Instantiating addon 'PQSModCreator' from assembly 'KopernicusExpansion.RegionalPQSMods'
[EXC 19:22:15.550] MissingMemberException: Cannot find property
        TriAxis.RunSharp.TypeInfo.FindProperty (System.Type t, System.String name, TriAxis.RunSharp.Operand[] indexes, System.Boolean static) (at <fd18e0ef899946d5b101c325
        TriAxis.RunSharp.Operand.Property (System.String name, TriAxis.RunSharp.ITypeMapper typeMapper, TriAxis.RunSharp.Operand[] indexes) (at <fd18e0ef899946d5b101c3255b
        TriAxis.RunSharp.Operand.Property (System.String name, TriAxis.RunSharp.ITypeMapper typeMapper) (at <fd18e0ef899946d5b101c3255bfcbde8>:0)
        TriAxis.RunSharp.ContextualOperand.Property (System.String name) (at <fd18e0ef899946d5b101c3255bfcbde8>:0)
        KopernicusExpansion.RegionalPQSMods.PQSModCreator.Awake () (at <1fa435b0150e4230a083fe6e8bedee29>:0)
        UnityEngine.DebugLogHandler:LogException(Exception, Object)
        ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
        UnityEngine.GameObject:AddComponent(Type)
        AddonLoader:StartAddon(LoadedAssembly, Type, KSPAddon, Startup)
        AddonLoader:StartAddons(Startup)
        <LoadObjects>d__90:MoveNext()
        UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
        <CreateDatabase>d__71:MoveNext()
        UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
        GameDatabase:StartLoad()
        <LoadSystems>d__11:MoveNext()
        UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
        LoadingScreen:Start()
```

This one is a new for me, so I'm not 100% sure, but it fits the overall M.O. of the AssemblyLoader borks. Remove Kopernicus from the `GameData` and see if the problem goes away. If yes, you will need to reach Kopernicus guys about this problem on `PQSModCreator`, it's complaining that something it expects to exist somewhere on the loaded DLLs are not there (i.e, it found the DLL it wants, but something inside it is not there).

Let me know if this is really the problem, this is a new and I need to know about it!

Cheers!

**Comment by Drehverschluss** [comment]
@Lisias 
You are awesome....thank you very much for your help. 
It was one of the "Kopernicus Expansion Continued" Mods.
Dont know exactly wich one but i dont really care. tweakscale works now and thats what i want :)

**Comment by Lisias** [comment]
> EDIT: Ok i tryed to find wich exactly it was. And it seems to be the "Kopernicus Expansion Continued - Regional PQSMods"

It's probably a missing or wrong versioned dependency (i.e., you have a too new or a too old DLL on your rig).

Kopernicus is a hell of an add'on, it opens a lot of possibilities to (ab)use :) TweakScale even more with the planet packs, I think it could be a good idea to reach the maintainers looking for guidance. It may be something they forgot to update somewhere, and so this would help a lot of more users!

I can't promise, as I have my hands already full, but I will try to give this a look next week - I use Kopernicus on a older KSP installment, and it's time to update it! (if I only had enough time to play with it!! hehehe!)

Cheers!

**Comment by Drehverschluss** [comment]
You dont have to.

I realised that the expension plugin allready got a update for 1.12 and thus are working together with your tweakscale.

So from my side the issue is closed :)

**Comment by Lisias** [comment]
Okie dokie!

Cheers!
