### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by natpi88** [net-lisias-ksp/TweakScale#233]
Something does not work, after changing the scale, the detail does not change, only the text

https://drive.google.com/file/d/1SZuTKZi7Z2oXPzsQej-9AXdUpVkLxTh3/view?usp=sharing

screens

https://drive.google.com/file/d/17n0HEpU7Vdd49yKGkQLitNqm2LFGN4wW/view?usp=sharing
https://drive.google.com/file/d/1vRs_K-O-xju9NvB9rFqTYvLcvzzS9fuF/view?usp=sharing
https://drive.google.com/file/d/1YQpoP3r40kWVEAfAdiiObZorcLMCMXlk/view?usp=sharing

**Comment by natpi88** [comment]
manual install after a few hours - reinstall, I find the mod incompatible with tweakscale. I want to believe that this will help someone
not working with BetterTimeWarp-2.2.0.0

**Comment by Lisias** [comment]
You misdiagnosed the problem. What's happening is that BetterTimeWarp is borking on load:

```
MechJeb caught a ReflectionTypeLoadException. Those DLL are not built for this KSP version:
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

BetterTimeWarp 2.1.0.0 GameData\BetterTimeWarp\BetterTimeWarp.dll
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

```

MechJeb si the one detecting the problem, not the perpetrator by the way.

Check with the BetterTimeWarp maintainer for how to fix it. It's not working for you right now

**Comment by Lisias** [comment]
Is the issue solved? Can I close this?

**Comment by Lisias** [comment]
Well. Closing it.

Cheers!
