### ISSUE TITLE
SEQ-9 Container Module and SEQ-3 Cargo Storage Unit have duplicated properties, fatal error.

### ISSUE THREAD

**Issue by littleconnor1** [net-lisias-ksp/TweakScale#234]
Send me an email at connor.simonelic@gmail.com for the log file, 133mb is too big for github apparently.

No clue what is causing this, but it's filed under Issue #34

**Comment by Lisias** [comment]
@littleconnor1 

> Send me an email at [connor.simonelic@gmail.com](mailto:connor.simonelic@gmail.com) for the log file, 133mb is too big for github apparently.

You can zip it and attach here too, but I'm sending you a email nevertheless.

What's happening is that someone is forcing their hand on TweakScale, instead of trying to cooperate. We need to find this patch and then ask the maintainer for a proper patching practice!

**Comment by Lisias** [comment]
Closing this by age.
