### ISSUE TITLE
AIES parts (and other mods I think) cannot be scaled when paired with Realism Overhaul. Is this intentional or...

### ISSUE THREAD

**Issue by harrytherocketeer** [net-lisias-ksp/TweakScale#235]

**Comment by harrytherocketeer** [comment]
The AIES configs in realism overhaul suggested mods folder have empty Tweakscale brackets in the configs.

**Comment by harrytherocketeer** [comment]
Uh hello?
@lisias

**Comment by harrytherocketeer** [comment]
Oh come on
Dont make me rewrite the configs alone :(

**Comment by Lisias** [comment]
Hi! I finally noticed this ! Sorry the delay, I (unfortunately) had to handle some less than pleasant problems on Forum, and I ended up neglecting the Issue Tracker a bit.

Let's see if I understood it correctly: you have problems with a thingy called AIES when using Realism Overhaul?

**Comment by Lisias** [comment]
@harrytherocketeer , Well… Just checked it.

https://github.com/KSP-RO/RealismOverhaul/blob/master/GameData/RealismOverhaul/RO_SuggestedMods/AIES/RO_AIES_Engine.cfg

The Realism Overhaul guys are **explicitly** removing TweakScale from the AIES engines. It's their choice.

I'm not familiarised with AIES. Where I can download it? It's this one?

https://www.curseforge.com/kerbal/ksp-mods/aies

**Comment by Lisias** [comment]
@harrytherocketeer , in order to shove back TweakScale support for AIES on R.O., we will need to overrule R.O. It's a fact that they delete TweakScale from some parts.

So even by adding back AIES patches for TweakScale, R.O. will remove them.

UNLESS we add `:AFTER[RealismOverhaul]` to the patches.

I think I would be picking a fight with R.O. guys by doing that. It's pretty unlikely that I will publish officially a patch-set for it.

I can help you on building your own patches for it, however. I just will not publish it on Forum or anywhere else.

Deal?

**Comment by harrytherocketeer** [comment]
> @harrytherocketeer , in order to shove back TweakScale support for AIES on R.O., we will need to overrule R.O. It's a fact that they delete TweakScale from some parts.
> 
> So even by adding back AIES patches for TweakScale, R.O. will remove them.
> 
> UNLESS we add `:AFTER[RealismOverhaul]` to the patches.
> 
> I think I would be picking a fight with R.O. guys by doing that. It's pretty unlikely that I will publish officially a patch-set for it.
> 
> I can help you on building your own patches for it, however. I just will not publish it on Forum or anywhere else.
> 
> Deal?

Absolutely.

**Comment by harrytherocketeer** [comment]
> @harrytherocketeer , Well… Just checked it.
> 
> https://github.com/KSP-RO/RealismOverhaul/blob/master/GameData/RealismOverhaul/RO_SuggestedMods/AIES/RO_AIES_Engine.cfg
> 
> The Realism Overhaul guys are **explicitly** removing TweakScale from the AIES engines. It's their choice.
> 
> I'm not familiarised with AIES. Where I can download it? It's this one?
> 
> https://www.curseforge.com/kerbal/ksp-mods/aies

Well actually you should also download AIES Patches on CKAN. And if you play with Textures Unlimited you can also install Magpie’s Mods for the config.

**Comment by harrytherocketeer** [comment]
@Lisias Is this ok, or am I missing anything else?
[AIES_TweakScale.txt](https://github.com/net-lisias-ksp/TweakScale/files/8224025/AIES_TweakScale.txt)

**Comment by Lisias** [comment]
@harrytherocketeer yes, I think this will do the trick!

Let me know if it worked. If not, I will build a testbed for it and try to figure out what happened in this weekend!

**Comment by harrytherocketeer** [comment]
> @harrytherocketeer yes, I think this will do the trick!
> 
> Let me know if it worked. If not, I will build a testbed for it and try to figure out what happened in this weekend!

So, umm...
that didnt work.
every patch i've added (after realismoverhaul) comes up as a mm warning, and tweakscale says there are fatal errors. While most probably unrelated I've also found issues with procedural fairings and ro tanks (mainly cant find the open interstage) and I would like to you to look over it as well.
[KSP.log](https://github.com/net-lisias-ksp/TweakScale/files/8239029/KSP.log)

**Comment by harrytherocketeer** [comment]
And most of all parts still cant be tweakscaled.
I transformed all of the tweakscale configs from PKMC, Restockplus, Squad/squadexpansion and AIES into text files, added :AFTER[RealismOverhaul] to the parts and then transformed it back into cfg files. Dont know if that was the proper way to modify the files or not.

**Comment by Lisias** [comment]
@harrytherocketeer 

> So, umm... that didnt work. every patch i've added (after realismoverhaul) comes up as a mm warning, and tweakscale says there are fatal errors. While most probably unrelated I've also found issues with procedural fairings and ro tanks (mainly cant find the open interstage) and I would like to you to look over it as well. [KSP.log](https://github.com/net-lisias-ksp/TweakScale/files/8239029/KSP.log)

The Errors are on the AIES Patches, you are gettinga lot of double patches:

```
[LOG 20:25:55.248] [TweakScale] ERROR: **FATAL** Part desacopladorsat3 (AIES SAT-3 Decoupler) has a fatal problem due having duplicated properties - see issue [#34]( https://github.com/net-lisias-ksp/TweakScale/issues/34 ). at error:0
[LOG 20:25:55.248] [TweakScale] ERROR: **FATAL** Part LRDecoupler (AIES LR Decoupler) has a fatal problem due having duplicated properties - see issue [#34]( https://github.com/net-lisias-ksp/TweakScale/issues/34 ). at error:0
[LOG 20:25:55.248] [TweakScale] ERROR: **FATAL** Part Separatormultifs (AIES Multi-FS Separator) has a fatal problem due having duplicated properties - see issue [#34]( https://github.com/net-lisias-ksp/TweakScale/issues/34 ). at error:0
[LOG 20:25:55.249] [TweakScale] ERROR: **FATAL** Part strutsoportec1 (AIES C1 Support Strut) has a fatal problem due having duplicated properties - see issue [#34]( https://github.com/net-lisias-ksp/TweakScale/issues/34 ). at error:0
[LOG 20:25:55.249] [TweakScale] ERROR: **FATAL** Part saltguia (AIES A1 'Saltguia' Laser) has a fatal problem due having duplicated properties - see issue [#34]( https://github.com/net-lisias-ksp/TweakScale/issues/34 ). at error:0
[LOG 20:25:55.249] [TweakScale] ERROR: **FATAL** Part batteryBAEr (AIES BAE-R Battery) has a fatal problem due having duplicated properties - see issue [#34]( https://github.com/net-lisias-ksp/TweakScale/issues/34 ). at error:0
[LOG 20:25:55.249] [TweakScale] ERROR: **FATAL** Part expendLandingLeg (AIES 'Expend' Landing Leg) has a fatal problem due having duplicated properties - see issue [#34]( https://github.com/net-lisias-ksp/TweakScale/issues/34 ). at error:0
[LOG 20:25:55.249] [TweakScale] ERROR: **FATAL** Part godLandingLeg2 (AIES GODEX-1B Landing Leg) has a fatal problem due having duplicated properties - see issue [#34]( https://github.com/net-lisias-ksp/TweakScale/issues/34 ). at error:0
[LOG 20:25:55.249] [TweakScale] ERROR: **FATAL** Part godLandingLeg (AIES GODEX-1A Landing Leg) has a fatal problem due having duplicated properties - see issue [#34]( https://github.com/net-lisias-ksp/TweakScale/issues/34 ). at error:0
[LOG 20:25:55.249] [TweakScale] ERROR: **FATAL** Part legstrotLandingLeg (AIES Legstrot Landing Leg) has a fatal problem due having duplicated properties - see issue [#34]( https://github.com/net-lisias-ksp/TweakScale/issues/34 ). at error:0
[LOG 20:25:55.249] [TweakScale] ERROR: **FATAL** Part xluzopl (AIES OPL-Lum Illuminator) has a fatal problem due having duplicated properties - see issue [#34]( https://github.com/net-lisias-ksp/TweakScale/issues/34 ). at error:0
[LOG 20:25:55.249] [TweakScale] ERROR: **FATAL** Part plommsLandingLeg (AIES PLOMM-S Landing Leg) has a fatal problem due having duplicated properties - see issue [#34]( https://github.com/net-lisias-ksp/TweakScale/issues/34 ). at error:0
```

And the reason is here:

```
[LOG 20:13:58.997] Applying update TweakScale/Deprecating/patches/AIES_TweakScale/@PART[desacopladorsat3] to AIES_Aerospace/Structure/AIESdesacoplador sat3/part.cfg/PART[desacopladorsat3]
…
ESdesacoplador sat3/part.cfg/PART[desacopladorsat3]
[LOG 20:15:54.297] Applying update TweakScale/patches/AIES_TweakScale/@PART[desacopladorsat3]:AFTER[RealismOverhaul] to AIES_Aerospace/Structure/AIESdesacoplador sat3/part.cfg/PART[desacopladorsat3]
```

You have **two** copies of the AIES patches on your TweakScale folder. You need to remove the TweakScale folder and resintall TweakScale. Salvage your changes first!

About the warnings, Module Manager is a pile of crap for debugging these. It tells us about the warnings, but don't list them.

```
[WRN 20:19:20.469] 11 warnings related to GameData/TweakScaleCompanion/PKMC/NFA/patches/Aero.cfg
[WRN 20:19:20.469] 1 warning related to GameData/TweakScaleCompanion/PKMC/NFA/patches/Control.cfg
[WRN 20:19:20.469] 7 warnings related to GameData/TweakScaleCompanion/PKMC/NFA/patches/Engine.cfg
[WRN 20:19:20.469] 8 warnings related to GameData/TweakScaleCompanion/PKMC/NFA/patches/Propulsion.cfg
[WRN 20:19:20.469] 16 warnings related to GameData/TweakScaleCompanion/PKMC/NFE/patches/Electrical.cfg
[WRN 20:19:20.469] 1 warning related to GameData/TweakScaleCompanion/PKMC/NFE/patches/Utility.cfg
[WRN 20:19:20.469] 24 warnings related to GameData/TweakScaleCompanion/PKMC/NFEX/patches/Communication.cfg
[WRN 20:19:20.469] 1 warning related to GameData/TweakScaleCompanion/PKMC/NFEX/patches/Control.cfg
[WRN 20:19:20.469] 1 warning related to GameData/TweakScaleCompanion/PKMC/NFEX/patches/Electrical.cfg
[WRN 20:19:20.469] 1 warning related to GameData/TweakScaleCompanion/PKMC/NFEX/patches/Ground.cfg
[WRN 20:19:20.469] 26 warnings related to GameData/TweakScaleCompanion/PKMC/NFEX/patches/Payload.cfg
[WRN 20:19:20.469] 8 warnings related to GameData/TweakScaleCompanion/PKMC/NFEX/patches/Pods.cfg
[WRN 20:19:20.469] 9 warnings related to GameData/TweakScaleCompanion/PKMC/NFLV/patches/Control.cfg
[WRN 20:19:20.469] 7 warnings related to GameData/TweakScaleCompanion/PKMC/NFLV/patches/Control.legacy.cfg
[WRN 20:19:20.469] 11 warnings related to GameData/TweakScaleCompanion/PKMC/NFLV/patches/Propulsion.cfg
[WRN 20:19:20.469] 12 warnings related to GameData/TweakScaleCompanion/PKMC/NFLV/patches/Structural.cfg
[WRN 20:19:20.469] 7 warnings related to GameData/TweakScaleCompanion/PKMC/NFP/patches/Control.cfg
[WRN 20:19:20.469] 19 warnings related to GameData/TweakScaleCompanion/PKMC/NFP/patches/Propulsion.cfg
[WRN 20:19:20.469] 1 warning related to GameData/TweakScaleCompanion/PKMC/NFP/patches/Science.cfg
[WRN 20:19:20.469] 1 warning related to GameData/TweakScaleCompanion/PKMC/NFP/patches/Utility.cfg
[WRN 20:19:20.469] 33 warnings related to GameData/TweakScaleCompanion/PKMC/NFS/patches/Electrical.cfg
[WRN 20:19:20.469] 7 warnings related to GameData/TweakScaleCompanion/PKMC/NFSC/patches/Control.cfg
[WRN 20:19:20.469] 6 warnings related to GameData/TweakScaleCompanion/PKMC/NFSC/patches/Engine.cfg
[WRN 20:19:20.469] 1 warning related to GameData/TweakScaleCompanion/PKMC/NFSC/patches/Ground.cfg
[WRN 20:19:20.469] 9 warnings related to GameData/TweakScaleCompanion/PKMC/NFSC/patches/Pods.cfg
[WRN 20:19:20.469] 1 warning related to GameData/TweakScaleCompanion/PKMC/NFSC/patches/Utility.cfg
[WRN 20:19:20.469] 57 warnings related to GameData/TweakScaleCompanion/ReStockPlus/Patches/ReStockPlus_TweakScale.cfg
```

> And most of all parts still cant be tweakscaled.
> I transformed all of the tweakscale configs from PKMC, Restockplus, Squad/squadexpansion and AIES into text files, added :AFTER[RealismOverhaul] to the parts and then transformed it back into cfg files. Dont know if that was the proper way to modify the files or not.

Yep. All that parts with that warnings are not being patched to TweakScale (if I'm right) probably due multiple temporal directives. So it's the same of not having added the `:AFTER` stunt.

BUT.

You also have a lot of parts double patched with B9PS and ModuleFuelTanks!!

```
[LOG 20:25:55.663] [TweakScale] ERROR: Part sspx-greenhouse-5-1 (9m Greenhouse) didn't passed the sanity check due having ModuleB9PartSwitch together ModuleFuelTanks - see issue [#12]( https://github.com/net-lisias-ksp/TweakScale/issues/12 ). at error:0
```

When this happens, TweakScale remove itself from the part, because these kind of problems blows up problems (because the B9PS deactivate itself but don't tells TweakScale it's deactivated, and when TweakScale tries to scale that part, B9PS blows up and TweakScale ends taking he heat).

These ones will give us some trouble, I suggest leaving them to be handled at last. We will need to create a patch to fix these parts by brute force.

**Comment by harrytherocketeer** [comment]
> @harrytherocketeer
> 
> > So, umm... that didnt work. every patch i've added (after realismoverhaul) comes up as a mm warning, and tweakscale says there are fatal errors. While most probably unrelated I've also found issues with procedural fairings and ro tanks (mainly cant find the open interstage) and I would like to you to look over it as well. [KSP.log](https://github.com/net-lisias-ksp/TweakScale/files/8239029/KSP.log)
> 
> The Errors are on the AIES Patches, you are gettinga lot of double patches:
> 
> ```
> [LOG 20:25:55.248] [TweakScale] ERROR: **FATAL** Part desacopladorsat3 (AIES SAT-3 Decoupler) has a fatal problem due having duplicated properties - see issue [#34]( https://github.com/net-lisias-ksp/TweakScale/issues/34 ). at error:0
> [LOG 20:25:55.248] [TweakScale] ERROR: **FATAL** Part LRDecoupler (AIES LR Decoupler) has a fatal problem due having duplicated properties - see issue [#34]( https://github.com/net-lisias-ksp/TweakScale/issues/34 ). at error:0
> [LOG 20:25:55.248] [TweakScale] ERROR: **FATAL** Part Separatormultifs (AIES Multi-FS Separator) has a fatal problem due having duplicated properties - see issue [#34]( https://github.com/net-lisias-ksp/TweakScale/issues/34 ). at error:0
> [LOG 20:25:55.249] [TweakScale] ERROR: **FATAL** Part strutsoportec1 (AIES C1 Support Strut) has a fatal problem due having duplicated properties - see issue [#34]( https://github.com/net-lisias-ksp/TweakScale/issues/34 ). at error:0
> [LOG 20:25:55.249] [TweakScale] ERROR: **FATAL** Part saltguia (AIES A1 'Saltguia' Laser) has a fatal problem due having duplicated properties - see issue [#34]( https://github.com/net-lisias-ksp/TweakScale/issues/34 ). at error:0
> [LOG 20:25:55.249] [TweakScale] ERROR: **FATAL** Part batteryBAEr (AIES BAE-R Battery) has a fatal problem due having duplicated properties - see issue [#34]( https://github.com/net-lisias-ksp/TweakScale/issues/34 ). at error:0
> [LOG 20:25:55.249] [TweakScale] ERROR: **FATAL** Part expendLandingLeg (AIES 'Expend' Landing Leg) has a fatal problem due having duplicated properties - see issue [#34]( https://github.com/net-lisias-ksp/TweakScale/issues/34 ). at error:0
> [LOG 20:25:55.249] [TweakScale] ERROR: **FATAL** Part godLandingLeg2 (AIES GODEX-1B Landing Leg) has a fatal problem due having duplicated properties - see issue [#34]( https://github.com/net-lisias-ksp/TweakScale/issues/34 ). at error:0
> [LOG 20:25:55.249] [TweakScale] ERROR: **FATAL** Part godLandingLeg (AIES GODEX-1A Landing Leg) has a fatal problem due having duplicated properties - see issue [#34]( https://github.com/net-lisias-ksp/TweakScale/issues/34 ). at error:0
> [LOG 20:25:55.249] [TweakScale] ERROR: **FATAL** Part legstrotLandingLeg (AIES Legstrot Landing Leg) has a fatal problem due having duplicated properties - see issue [#34]( https://github.com/net-lisias-ksp/TweakScale/issues/34 ). at error:0
> [LOG 20:25:55.249] [TweakScale] ERROR: **FATAL** Part xluzopl (AIES OPL-Lum Illuminator) has a fatal problem due having duplicated properties - see issue [#34]( https://github.com/net-lisias-ksp/TweakScale/issues/34 ). at error:0
> [LOG 20:25:55.249] [TweakScale] ERROR: **FATAL** Part plommsLandingLeg (AIES PLOMM-S Landing Leg) has a fatal problem due having duplicated properties - see issue [#34]( https://github.com/net-lisias-ksp/TweakScale/issues/34 ). at error:0
> ```
> 
> And the reason is here:
> 
> ```
> [LOG 20:13:58.997] Applying update TweakScale/Deprecating/patches/AIES_TweakScale/@PART[desacopladorsat3] to AIES_Aerospace/Structure/AIESdesacoplador sat3/part.cfg/PART[desacopladorsat3]
> …
> ESdesacoplador sat3/part.cfg/PART[desacopladorsat3]
> [LOG 20:15:54.297] Applying update TweakScale/patches/AIES_TweakScale/@PART[desacopladorsat3]:AFTER[RealismOverhaul] to AIES_Aerospace/Structure/AIESdesacoplador sat3/part.cfg/PART[desacopladorsat3]
> ```
> 
> You have **two** copies of the AIES patches on your TweakScale folder. You need to remove the TweakScale folder and resintall TweakScale. Salvage your changes first!
> 
> About the warnings, Module Manager is a pile of crap for debugging these. It tells us about the warnings, but don't list them.
> 
> ```
> [WRN 20:19:20.469] 11 warnings related to GameData/TweakScaleCompanion/PKMC/NFA/patches/Aero.cfg
> [WRN 20:19:20.469] 1 warning related to GameData/TweakScaleCompanion/PKMC/NFA/patches/Control.cfg
> [WRN 20:19:20.469] 7 warnings related to GameData/TweakScaleCompanion/PKMC/NFA/patches/Engine.cfg
> [WRN 20:19:20.469] 8 warnings related to GameData/TweakScaleCompanion/PKMC/NFA/patches/Propulsion.cfg
> [WRN 20:19:20.469] 16 warnings related to GameData/TweakScaleCompanion/PKMC/NFE/patches/Electrical.cfg
> [WRN 20:19:20.469] 1 warning related to GameData/TweakScaleCompanion/PKMC/NFE/patches/Utility.cfg
> [WRN 20:19:20.469] 24 warnings related to GameData/TweakScaleCompanion/PKMC/NFEX/patches/Communication.cfg
> [WRN 20:19:20.469] 1 warning related to GameData/TweakScaleCompanion/PKMC/NFEX/patches/Control.cfg
> [WRN 20:19:20.469] 1 warning related to GameData/TweakScaleCompanion/PKMC/NFEX/patches/Electrical.cfg
> [WRN 20:19:20.469] 1 warning related to GameData/TweakScaleCompanion/PKMC/NFEX/patches/Ground.cfg
> [WRN 20:19:20.469] 26 warnings related to GameData/TweakScaleCompanion/PKMC/NFEX/patches/Payload.cfg
> [WRN 20:19:20.469] 8 warnings related to GameData/TweakScaleCompanion/PKMC/NFEX/patches/Pods.cfg
> [WRN 20:19:20.469] 9 warnings related to GameData/TweakScaleCompanion/PKMC/NFLV/patches/Control.cfg
> [WRN 20:19:20.469] 7 warnings related to GameData/TweakScaleCompanion/PKMC/NFLV/patches/Control.legacy.cfg
> [WRN 20:19:20.469] 11 warnings related to GameData/TweakScaleCompanion/PKMC/NFLV/patches/Propulsion.cfg
> [WRN 20:19:20.469] 12 warnings related to GameData/TweakScaleCompanion/PKMC/NFLV/patches/Structural.cfg
> [WRN 20:19:20.469] 7 warnings related to GameData/TweakScaleCompanion/PKMC/NFP/patches/Control.cfg
> [WRN 20:19:20.469] 19 warnings related to GameData/TweakScaleCompanion/PKMC/NFP/patches/Propulsion.cfg
> [WRN 20:19:20.469] 1 warning related to GameData/TweakScaleCompanion/PKMC/NFP/patches/Science.cfg
> [WRN 20:19:20.469] 1 warning related to GameData/TweakScaleCompanion/PKMC/NFP/patches/Utility.cfg
> [WRN 20:19:20.469] 33 warnings related to GameData/TweakScaleCompanion/PKMC/NFS/patches/Electrical.cfg
> [WRN 20:19:20.469] 7 warnings related to GameData/TweakScaleCompanion/PKMC/NFSC/patches/Control.cfg
> [WRN 20:19:20.469] 6 warnings related to GameData/TweakScaleCompanion/PKMC/NFSC/patches/Engine.cfg
> [WRN 20:19:20.469] 1 warning related to GameData/TweakScaleCompanion/PKMC/NFSC/patches/Ground.cfg
> [WRN 20:19:20.469] 9 warnings related to GameData/TweakScaleCompanion/PKMC/NFSC/patches/Pods.cfg
> [WRN 20:19:20.469] 1 warning related to GameData/TweakScaleCompanion/PKMC/NFSC/patches/Utility.cfg
> [WRN 20:19:20.469] 57 warnings related to GameData/TweakScaleCompanion/ReStockPlus/Patches/ReStockPlus_TweakScale.cfg
> ```
> 
>  > And most of all parts still cant be tweakscaled.
> > I transformed all of the tweakscale configs from PKMC, Restockplus, Squad/squadexpansion and AIES into text files, added :AFTER[RealismOverhaul] to the parts and then transformed it back into cfg files. Dont know if that was the proper way to modify the files or not.
> 
> Yep. All that parts with that warnings are not being patched to TweakScale (if I'm right) probably due multiple temporal directives. So it's the same of not having added the `:AFTER` stunt.
> 
> BUT.
> 
> You also have a lot of parts double patched with B9PS and ModuleFuelTanks!!
> 
> ```
> [LOG 20:25:55.663] [TweakScale] ERROR: Part sspx-greenhouse-5-1 (9m Greenhouse) didn't passed the sanity check due having ModuleB9PartSwitch together ModuleFuelTanks - see issue [#12]( https://github.com/net-lisias-ksp/TweakScale/issues/12 ). at error:0
> ```
> 
> When this happens, TweakScale remove itself from the part, because these kind of problems blows up problems (because the B9PS deactivate itself but don't tells TweakScale it's deactivated, and when TweakScale tries to scale that part, B9PS blows up and TweakScale ends taking he heat).
> 
> These ones will give us some trouble, I suggest leaving them to be handled at last. We will need to create a patch to fix these parts by brute force.

What about if we just…you know, remove the empty Tweakscale module from RO?

**Comment by harrytherocketeer** [comment]
Wait nah, that still didnt work.
At least I installed ro engines for different types, but damn, still dont like spamming 24 NFLV engines just for the first stage, because the F-1 is too damn inefficent.

**Comment by Lisias** [comment]
@harrytherocketeer 

> What about if we just…you know, remove the empty Tweakscale module from RO?

It will prevent the existing patches from being removed, but will not add patches by itself.


> Wait nah, that still didnt work.

it should had solved at least some of the problems. What happened? The patched engines didn't scaled, or scaled badly?

**Comment by harrytherocketeer** [comment]
> @harrytherocketeer
> 
> > What about if we just…you know, remove the empty Tweakscale module from RO?
> 
> It will prevent the existing patches from being removed, but will not add patches by itself.
> 
> > Wait nah, that still didnt work.
> 
> it should had solved at least some of the problems. What happened? The patched engines didn't scaled, or scaled badly?

It didn’t even have the Tweakscale bar when I right-clicked on it.
Some of the probe cores and batteries can still be scaled, but I think that’s about all.

**Comment by Lisias** [comment]
@harrytherocketeer

> It didn’t even have the Tweakscale bar when I right-clicked on it. Some of the probe cores and batteries can still be scaled, but I think that’s about all.

So we have the answer: we need patches.

There's an easy way out, but the scalings will not be that plausible. Use All Tweak.

https://forum.kerbalspaceprogram.com/index.php?/topic/182700-111x-all-tweak-07-23rdoctober2019/

Try it on a test savegame to see if it will attend your needs as is before risking your valuables savegames.

I think we will need to write some custom ScaleTypes, but perhaps we get lucky. :)

**Comment by harrytherocketeer** [comment]
> @harrytherocketeer
> 
> > It didn’t even have the Tweakscale bar when I right-clicked on it. Some of the probe cores and batteries can still be scaled, but I think that’s about all.
> 
> So we have the answer: we need patches.
> 
> There's an easy way out, but the scalings will not be that plausible. Use All Tweak.
> 
> https://forum.kerbalspaceprogram.com/index.php?/topic/182700-111x-all-tweak-07-23rdoctober2019/
> 
> Try it on a test savegame to see if it will attend your needs as is before risking your valuables savegames.
> 
> I think we will need to write some custom ScaleTypes, but perhaps we get lucky. :)

It types every part to 1.25m, but hey, at least it works!

**Comment by harrytherocketeer** [comment]
Now no more having to attack 36 NK-33s just for my rocket to work!

**Comment by Lisias** [comment]
@harrytherocketeer 

> It types every part to 1.25m, but hey, at least it works!

Yep, but at least it kinda works (most of the time). There's a few parts that misbehave, but these we can handle one by one later.

I will work something on TweakScale (see #236) so it will be safer to change ScaleTypes (the thingy All Tweak shoves everywhere as the same), so you can install new TweakScale patches after installing All Tweak.

Currently, it's not advised to install new patches for existing parts because this may confuse TweakScale later on crafts on flight.

Cheers!

**Comment by harrytherocketeer** [comment]
> @harrytherocketeer
> 
> > It types every part to 1.25m, but hey, at least it works!
> 
> Yep, but at least it kinda works (most of the time). There's a few parts that misbehave, but these we can handle one by one later.
> 
> I will work something on TweakScale (see #236) so it will be safer to change ScaleTypes (the thingy All Tweak shoves everywhere as the same), so you can install new TweakScale patches after installing All Tweak.
> 
> Currently, it's not advised to install new patches for existing parts because this may confuse TweakScale later on crafts on flight.
> 
> Cheers!

Also my friends at the RO discord always ask me why the hell do I have a Scaletype on Procedural mods

**Comment by harrytherocketeer** [comment]
Also how do Tweakscale calculate the new volume of a tweakscaled cylindrical tank/solid booster? Or does it still use the regular cube volume formula?

**Comment by Lisias** [comment]
> Also my friends at the RO discord always ask me why the hell do I have a Scaletype on Procedural mods

Well, because someone patched TweakScale on them! :)

Imagine that you made a very nice cargo lifter using Procedural Wings. And now you need a bigger one.

What would be easier: to TweakScale up the root part and having everything scaled up for you, and then start to work on the places where TS didn't worked as expected (as cockpits), or to remove the wings and redo them from scratch trying hard to make them similar to the previous one? ;)


> Also how do Tweakscale calculate the new volume of a tweakscaled cylindrical tank/solid booster? Or does it still use the regular cube volume formula?

The way you want it to be scaled (as long is an exponential), but by default using the regular cube formula.

Cheers!

**Comment by Lisias** [comment]
Closing this by age.
