### ISSUE TITLE
missing DLL error

### ISSUE THREAD

**Issue by derpninja23** [net-lisias-ksp/TweakScale#242]
whenever I boot up the game, tweakscale tells me that it is missing DLLs.
"missing class: The type initializer for 'KSPe.IO.Hierarchy.1' threw an exception".
bug report: [KSPBugReport_2022-04-13_010736.zip](https://github.com/net-lisias-ksp/TweakScale/files/8478913/KSPBugReport_2022-04-13_010736.zip)
and yes I know everything else is broken too, ill sort that out later.

**Comment by Lisias** [comment]
@derpninja23 

You have a problem with KSP Community Fixes.

```
[LOG 00:39:47.523] [AddonLoader]: Instantiating addon 'KSPBugReport' from assembly 'KSPBugReport'
[ERR 00:39:47.524] [AddonLoader]: Exception iterating assemblies: Exception of type 'System.Reflection.ReflectionTypeLoadException' was thrown.

Additional information about this exception:

 System.TypeLoadException: Could not load type of field 'KSPCommunityFixes.KSPCommunityFixes <Harmony>k__BackingField' (1) due to
: Could not load file or assembly '0Harmony, Version=2.0.4.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. assembly:0Harmony, Version=2.0.4.0, Culture=neutral, PublicKeyToken=null type:<unknown type> member:(null) signature:<none>
```

Reach KSP Community Fixes maintainer for further help. This is triggering a bug on KSP on a thingy called Assembly Resolver, and this bug screws up **everything** that tries to load an DLL or to use Reflection later.

**Comment by Lisias** [comment]
Hi, @derpninja23 ! Your problem was solved? Can I close this ticket?

**Comment by Lisias** [comment]
Closing this, assuming the user's problem was solved.
