### ISSUE TITLE
New bug related to IVA and Cameras when TweakScale is installed

### ISSUE THREAD

**Issue by Lisias** [net-lisias-ksp/TweakScale#246]
From KSP 1.4.x (tested on KSP 1.4.3) to KSP 1.12.3, if the user saves the game (or quicksave) while the camera is focused on a ~~Breaking Ground Inventory part~~ I[EDIT: nope! to any craft!!]*, once the user load it back all Crafts with IVA are screwed up until the user saves the game again and reload, but with the camera focusing something else (as a Kerbal or a Craft with normal parts).

Switching to the Tracking Station and reselecting a craft from there is also reported to fix the misbehaviour.

### 1

Build a minimal craft like this (this craft is available on the savegame below). Shove on some inventory one of the parts of the Cargo Category depicted below:

![screenshot35](https://user-images.githubusercontent.com/64334/165857239-95b4e4b2-89ac-4aa2-a44d-7e907cd59473.png)

### 2

Launch the thing:

![screenshot36](https://user-images.githubusercontent.com/64334/165857414-47b262d7-fea7-4ffd-8b3a-4cf43fdfe3f4.png)

### 3

Do a EVA, and grasp the part into the Kerbal's inventory:

![screenshot37](https://user-images.githubusercontent.com/64334/165857497-b009e442-39ca-468b-8c30-ade671a9ce50.png)

### 4

Drop the part into the ground:

![screenshot38](https://user-images.githubusercontent.com/64334/165857548-71175a62-40f8-43d8-b972-a273b77109ad.png)

![screenshot39](https://user-images.githubusercontent.com/64334/165857558-e312fe98-b3d2-4ae8-8e2b-f4f62d0029aa.png)

### 5

Go back to the craft and board it:

![screenshot40](https://user-images.githubusercontent.com/64334/165857611-9bd96bf5-ee04-446d-b221-658681c77f6e.png)

![screenshot41](https://user-images.githubusercontent.com/64334/165857621-a5e61d3a-0e6e-4889-8b59-f327a9cd52d4.png)

Note the portrait on the bottom right.

### 6

Do a quicksave, and then reload from it:

![screenshot42](https://user-images.githubusercontent.com/64334/165857757-290a8d8b-5e45-4b27-b315-707f136fe82d.png)

![screenshot43](https://user-images.githubusercontent.com/64334/165857769-61f3179a-57f2-4b59-bea8-2ac5ac59693e.png)

### 7 Evidence of Good Behaving

Note that the Kerbal is being shown on the Portrait, and by hitting "C" the IVA is being displayed correctly.

![screenshot44](https://user-images.githubusercontent.com/64334/165857920-182e4bf7-0651-4c03-998a-da3af3576ed7.png)

![screenshot46](https://user-images.githubusercontent.com/64334/165857941-4a250cf6-6c2d-4730-8fa4-aa9c55c51dd7.png)

### 8 Triggering the problem

Hit `[` to switch to the Portable RTG (or whatever part you selected), do a quicksave and reload from it:

![screenshot47](https://user-images.githubusercontent.com/64334/165858035-b2da17cf-b3b9-427e-8b15-0f33f7631f76.png)

![screenshot48](https://user-images.githubusercontent.com/64334/165858045-e541dce5-58ea-49d8-b308-8417639061ae.png)

![screenshot49](https://user-images.githubusercontent.com/64334/165858057-9c5dab38-1f01-41f3-9082-165465ce693e.png)

### 9 Problem triggered

Hit `]` again to switch back to the Command Pod.

Note the Portrait is now full black, and the by hitting "C" (IVA), there's no IVA at all! 

![screenshot50](https://user-images.githubusercontent.com/64334/165858164-10d14e4e-53a1-4b18-87d4-ad3851831d03.png)

![screenshot51](https://user-images.githubusercontent.com/64334/165858275-a1e26c98-b350-49f9-bbc1-1e64b4b0c99e.png)

![screenshot52](https://user-images.githubusercontent.com/64334/165858319-e60e7b0f-ef74-4a40-abb3-60a80fc31644.png)

### 10 Restoring the good behaviour

Do another quicksave and reload from it:

![screenshot53](https://user-images.githubusercontent.com/64334/165858444-b53e6efb-de69-4883-aa2a-a82168f3a571.png)

![screenshot54](https://user-images.githubusercontent.com/64334/165858453-1d57e7e7-8817-4afc-9f31-f190cbdbb73f.png)

Problem solved.

Switching into Tracking Station scene and from there to a vessel is also known to "fix" the problem.

## Evidences

* Savegame: [bug-ksp-iva.zip](https://github.com/net-lisias-ksp/KSP-Recall/files/8586981/bug-ksp-iva.zip)
* KSP.log: [KSP.log](https://github.com/net-lisias-ksp/KSP-Recall/files/8586988/KSP.log)

**Comment by Lisias** [comment]
The problem was simpler that that. Once you load a Savegame, all the crafts **but** the one was focused got the IVA screwed. The problem was happening using a Breaking Ground part just because it has no IVA, but anything, virtually **anything** being loaded up without the Camera focus lose the IVA!

It was detected a bad move on TweakScale code itself.

Savegame with the evidence:
[bug-iva.zip](https://github.com/net-lisias-ksp/TweakScale/files/8594606/bug-iva.zip)

**Comment by Lisias** [comment]
The bug probably affects KSP 1.3.1 too - but didn't bored to check.

**Comment by Lisias** [comment]
Fixed on commit https://github.com/net-lisias-ksp/TweakScale/commit/b5b3645f4fbabb3d6b6c02a1ecde8fca75fa532d

(damn!!!)

**Comment by Lisias** [comment]
Fixed on commit https://github.com/net-lisias-ksp/TweakScale/commit/c0462140771f5fd800feaa8f09307ddb78d5a604

(damn!!!)

**Comment by Lisias** [comment]
Fellow Kerbonaut [Jezzick](https://forum.kerbalspaceprogram.com/index.php?/profile/175940-jezzick/) found [reported](https://forum.kerbalspaceprogram.com/index.php?/topic/179030-ksp-130-tweakscale-under-lisias-management-24616-2022-0713/&do=findComment&comment=4157000) a new misbehaviour related to this issue on forum:

> Steps to reproduce :
> 
> with a new KSP install
> 
> Install TweakScale and dependencies listed above
> 
> Start a new flight with the acapello stock rocket
> 
> upon flight scene initilization, Kerbal Portraits and IVA and Interior overlay are all empty
> 
> (Switching away from active scene and back fixes the issue - as mentioned in the github issue#246) 
>
> ![](https://i.imgur.com/loXyYOM.png)
>
> ![](https://i.imgur.com/tG0STzX.png)

Logs were omitted as I detected they are not relevant to this problem.

However, the report missed this important step: the craft must be launched directly into the launchpad or runway - launching it from Editor **does not** triggers the problem!

I'm reopening this so.

**Comment by DaniAngione** [comment]
Heya!

I have this issue as well (the IVA portrait on bottom right being black and switching to IVA "Moving" the camera inside the ship but no interior existing)

However for me I don't need to follow any steps or anything. It just happens on every craft from the moment the game launches. I have quite a big mod list but simply removing TweakScale makes it work (that's how I got here, I removed a lot of mods to test/find what was wrong)

I'm using the latest game version and mod version as provided by CKAN

Let me know what other info you may need!

**Comment by Lisias** [comment]
Thanks for the report, @DaniAngione . It's indeed a bug on TweakScale, in some situations it's utterly screwing up the IVA scaling (I think it's using 0 as scale by accident).

**Comment by c6ForH66** [comment]
@Lisias  I have the same problem. IVA will not working if I launch from Launchpad or Runway.

**Comment by G3NTs** [comment]
I found myself having the same issue. Is there any quick way of fixing it? Love the mod btw!

**Comment by Lisias** [comment]
> I found myself having the same issue. Is there any quick way of fixing it? Love the mod btw!

Sorry for that.

I'm still fighting to dig some time in order to fix this one - it appears to be a pretty stupid mistake on the code, some value not being initialised on a specific situation - so I need to burn time debugging the damned thing until I find the issue - and time for this is exactly what I'm short of right now.

A work around is to switch to Tracking Station and then back to the vessel. It's also a hint for where I need to start looking, by the way.

**Comment by Lisias** [comment]
Hey, while refactoring the IVA code in order to purse this issue, I ended up fixing it by accident!

See commit https://github.com/net-lisias-ksp/TweakScale/commit/082a1b620e0fc9ae306f92435c4d810176c77a03
