### ISSUE TITLE
Unfixable 999_Scale_Redlist.dll

### ISSUE THREAD

**Issue by KommandantGalileo** [net-lisias-ksp/TweakScale#253]
The 999_Scale_Redlist.dll error is constantly coming up, even if I have properly installed it and there are no duplicates of it.

**Comment by Lisias** [comment]
Hi, @KommandantGalileo .

I need your **FULL** KSP.log . Drag and drop it on a post on this thread so I can inspect it.

If you are using MechJeb2, please temporarily uninstall it. MJ2 somehow screws up badly the order in which the events happens, and it's exactly that order what matters while diagnosing the problem.

(as you using CKAN?)

**Comment by Lisias** [comment]
This issue will be make impossible to happen as soon as https://github.com/net-lisias-ksp/ModuleManagerWatchDog/issues/5 is put into "production", on TS 2.4.7.0
