### ISSUE TITLE
CKAN not picking up latest?

### ISSUE THREAD

**Issue by scottsen** [net-lisias-ksp/TweakScale#53]
I am still seeing 2.4.2 on CKAN - shouldn't I see 2.4.3 ?

**Comment by Lisias** [comment]
Hi @scottsen . 

As you can see in the Forum, I'm being extra cautious on this release as I would overwhelm me with reports.

A lot of fixes are being applied on what will be the 2.4.3.1 release, and if everything goes well, it would reach CKAN by Sunday.

**Comment by Lisias** [comment]
Being not exactly a bug, but a release scheduling decision, I'm closing this.

**Comment by scottsen** [comment]
Thank you! :)

**Comment by Lisias** [comment]
Do you remember when I said Sunday? (sigh)

It will took some Sundays more, sorry. But it **WILL** be released on a Sunday. :)
