### ISSUE TITLE
[ERR ***FATAL*** link provided in KSP.log links to 404

### ISSUE THREAD

**Issue by zer0Kerbal** [net-lisias-ksp/TweakScale#54]
link created in KSP.log has an additional '.' at the end causing linking to correct URL to fail and hit a 404.

"https://github.com/net-lisias-ksp/TweakScale/issues/34." is what is being linked in npp.

steps:
load KSP and have TweakScale yell about 
[WRN 00:06:51.967] [TweakScale] **FATAL** Found a showstopper problem on [PART].
[ERR 00:06:51.967] [TweakScale] **FATAL** Part  [PART] has a fatal problem due having duplicated properties - see issue #34 - https://github.com/net-lisias-ksp/TweakScale/issues/34.
open log in URL enabled editor/reader after is is flushed to disk.
click on link. 
404.

**Comment by Lisias** [comment]
Thanks for the heads up. It's an obvious error, but the thing was working on the release - so I  missed that.

Will be fixed in the next minor release.

**Comment by Lisias** [comment]
Nope. The code is fine. Something changed somewhere else.

```
            dlg.Show(
                "Houston, we have a Problem!",
                String.Format(MSG, failure_count),
                () => { Application.OpenURL("https://forum.kerbalspaceprogram.com/index.php?/topic/179030-*"); },
                win, text
            );
```

**Comment by Lisias** [comment]
Now I understand. It's a typo on the log message. Will be corrected. :)

**Comment by zer0Kerbal** [comment]
all good. low priority - just trying to help. I really appreciate this change! (as in the notification).

**Comment by Lisias** [comment]
Trying mimicking MarkDown styled links - help to emphasis the link and surround them with disallowed chars for URL. Let's see if this stunt sticks. :)

commit: https://github.com/net-lisias-ksp/TweakScale/commit/96320420fe1fd1c63ecf8b76e218f49079e3a81f
