### ISSUE TITLE
Mk4 System Patch (addendum)

### ISSUE THREAD

**Issue by deimos790** [net-lisias-ksp/TweakScale#58]
This causes conflict...
```

@PART[mk4cockpit*] // 
{
    %MODULE[TweakScale]
    {
        type = stack
		defaultScale = 5.0
    }
}

@PART[mk4cockpit-shoulder*] // 
{
    %MODULE[TweakScale]
    {
        type = surface
    }
}
```

**Comment by Lisias** [comment]
Yes, thank you for the report.

It's already fixed on this [commit](https://github.com/net-lisias-ksp/TweakScale/commit/4aed1a947dc8b4da313cf1bfb1fa9f7f93efa56e) to be included on the next 2.4.3.1 release.

Thanks again!

**Comment by Annastasya77** [comment]
Line 241 causes 3 Issue #34 Fatal errors still even after your commit changes to MarkIVSystem_TweakScale.cfg. Judging by your change for cockpits I'm guessing you would also want an edit something like this:

@part[mk4cockpit-shoulder-1,mk4cockpit-shoulder-2,mk4cockpit-shoulder-3] //


[KSP (Truncated for upload size).log](https://github.com/net-lisias-ksp/TweakScale/files/3374904/KSP.Truncated.for.upload.size.log)

**Comment by Lisias** [comment]
Fair enough. @Annastasya77 has a point, it's a good addendum to @deimos790 's report

**Comment by Lisias** [comment]
Fixed on on commit: https://github.com/net-lisias-ksp/TweakScale/commit/c5f201f11db3602be9ac29c52c40d06a560b9599
