### ISSUE TITLE
*FATAL* warnings on startup

### ISSUE THREAD

**Issue by byongtube** [net-lisias-ksp/TweakScale#60]
I just had that scary warning titled: HOUSTON WE HAVE A PROBLEM

![image](https://user-images.githubusercontent.com/35516339/61280165-5f0b2180-a7f2-11e9-8d9e-d2057960af2a.png)

Therefore, I am contacting you here.

KSP.log file is down below, but to save your time, the error was from:

> [WRN 17:34:26.307] [TweakScale] **FATAL** Found a showstopper problem on awacsRadar
[ERR 17:34:26.307] [TweakScale] **FATAL** Part awacsRadar has a fatal problem due having duplicated properties - see issue #34 - https://github.com/net-lisias-ksp/TweakScale/issues/34.

> [WRN 17:34:26.333] [TweakScale] **FATAL** Found a showstopper problem on arrestingHook.
[ERR 17:34:26.333] [TweakScale] **FATAL** Part arrestingHook has a fatal problem due having duplicated properties - see issue #34 - https://github.com/net-lisias-ksp/TweakScale/issues/34.

These might have to do something with BDArmory and the second issue might have to do with TM5.

[KSP.log](https://github.com/net-lisias-ksp/TweakScale/files/3396123/KSP.log)

Many thanks,

EDIT: ACA had nothing to do with this issue, its just BD and TM5.

**Comment by Lisias** [comment]
Hi. Thanks for reaching me here! :)

I looked into your KSP.log, and I think I found the problem:

```
BDArmory/Localization/part_deformatter/@PART[awacsRadar]:FINAL
BDArmory/MMPatches/BDA_TweakScale/@PART[awacsRadar]  <— here
BDArmory/Parts/awacsRadar/awacsRadar/awacsRadar
TMasterson5TweakscalePatches/BDArmoryTweakscale/tweakscaleConfigPatch/@PART[awacsRadar < — here
```

There're two guys patching awacsRadar for TweakScale at the same time. I think you should edit the patch from TMasterson5 to delete its patch for awacsRadar and arrestingHook .

In time, can I recommend the use of [S.A.V.E.](https://forum.kerbalspaceprogram.com/index.php?/topic/94997-171-save-automatic-backup-system-155-3121/)? (this would had saved me a lot of headaches in the past!! :D)

**Comment by Lisias** [comment]
Let me know if this fixed your issue, so I can close this issue!

**Comment by byongtube** [comment]
I have no access to my desktop right now so I will try in the weekends and update here. Thanks for your help!

**Comment by byongtube** [comment]
I have fixed the issue with the method that you've told me. Thank you for your help.
I have the same problem for SM's mods, so I will start a new issue on it.
