### ISSUE TITLE
Support for new Cryo Engines

### ISSUE THREAD

**Issue by friznit** [net-lisias-ksp/TweakScale#65]
I've added the new Cryo engines to Nerta_Tweakscale.cfg.  I left the legacy ones in for now until they are deprecated.  It's such a small change it's not worth a PR!  File attached (txt cos github things)

[Nerta_Tweakscale.txt](https://github.com/net-lisias-ksp/TweakScale/files/3441270/Nerta_Tweakscale.txt)

**Comment by Lisias** [comment]
Whoops… I totally lost this one.

These exact changes were applied on [pull request #64](https://github.com/net-lisias-ksp/TweakScale/pull/64).

Thanks!
