### ISSUE TITLE
270 FATAL "duplicated properties" errors on STOCK parts after updating TweakScale + other mods

### ISSUE THREAD

**Issue by IanThePineapple** [net-lisias-ksp/TweakScale#67]
Version: KSP 1.7.3, with Making History + Breaking Ground
OS: Windows 10 64bit

I'll be honest, I have no idea what's happening. I tried both .3.1 and .3, and they produced the same results. However, .2 worked, and I am now using it (only issue is sometimes loading crafts say "Unknown part modules, TweakScale.disabled". I didn't try loading any saves, I just Alt+F4'ed out when I saw the error message.
I looked into the log and saw the mess that seemed to be every stock part having a FATAL error.

I added a screenshot of the message, by gamedata, the .log (look towards the bottom for the FATALs), the output.txt from the main KSP folder, and the output.txt from the KSP_64x_Data folder. Thanks for the help!

![screenshot524](https://user-images.githubusercontent.com/53544283/62256291-ad154d00-b3ce-11e9-8b72-f31aeedec5b2.png)

![image](https://user-images.githubusercontent.com/53544283/62257869-b48c2480-b3d5-11e9-95d8-b4b7f19022dc.png)

![image](https://user-images.githubusercontent.com/53544283/62257890-d1285c80-b3d5-11e9-8645-cdc96c944e0d.png)

![image](https://user-images.githubusercontent.com/53544283/62257902-dc7b8800-b3d5-11e9-85e6-8bf67a9e3825.png)

[KSP.log](https://github.com/net-lisias-ksp/TweakScale/files/3454304/KSP.log)

[output_log.txt](https://github.com/net-lisias-ksp/TweakScale/files/3454303/output_log.txt)

[output_log.txt](https://github.com/net-lisias-ksp/TweakScale/files/3454348/output_log.txt)

**Comment by Lisias** [comment]
Things on your KSP installment are somewhat messy. Besides the **FATAL** problems (problems that can corrupt savegames), I found a lot of what follows:

```
[ERR 19:49:43.067] [TweakScale] Exception on writeDryCost: System.NullReferenceException: Object reference not set to an instance of an object
  at TweakScale.PrefabDryCostWriter.WriteDryCost () [0x00000] in <filename unknown>:0

[LOG 19:49:43.068] [TweakScale] part=ITSLeg-L (LT-37L Landing Gear)
[ERR 19:49:43.068] [TweakScale] Exception on writeDryCost: System.NullReferenceException: Object reference not set to an instance of an object
  at TweakScale.PrefabDryCostWriter.WriteDryCost () [0x00000] in <filename unknown>:0

[LOG 19:49:43.068] [TweakScale] part=KRE-AeroLeg-L (LT-37L Landing Gear)
```

**Comment by Lisias** [comment]
Hummm… Wait.

```
[LOG 19:47:40.708] Config(@PART[turboFanEngine]) TweakScale/patches/Squad/Squad_Engines/@PART[turboFanEngine]
[LOG 19:47:41.023] Config(@PART[turboFanEngine]) TweakScale-v2.3.10/TweakScale/patches/Squad/Squad_Engines/@PART[turboFanEngine]
```

You forgot an old TweakScale on your KSP installment! :)

delete `GameData/TweakScale-v2.3.10/` and most (if not all) the problems will vanish.

If something ends left behind, advise me here with a new KSP.log and I will check it!

**Comment by Lisias** [comment]
Waiting for the reporter to confirm the solution.

**Comment by IanThePineapple** [comment]
> 
> 
> Hummm… Wait.
> 
> ```
> [LOG 19:47:40.708] Config(@PART[turboFanEngine]) TweakScale/patches/Squad/Squad_Engines/@PART[turboFanEngine]
> [LOG 19:47:41.023] Config(@PART[turboFanEngine]) TweakScale-v2.3.10/TweakScale/patches/Squad/Squad_Engines/@PART[turboFanEngine]
> ```
> 
> You forgot an old TweakScale on your KSP installment! :)
> 
> delete `GameData/TweakScale-v2.3.10/` and most (if not all) the problems will vanish.
> 
> If something ends left behind, advise me here with a new KSP.log and I will check it!

Thank you so much, it worked!
