### ISSUE TITLE
Doesn't Work

### ISSUE THREAD

**Issue by rollingdeep1026** [net-lisias-ksp/TweakScale#80]
![2019-10-21 (5)](https://user-images.githubusercontent.com/56784962/67170245-19f31e80-f3e3-11e9-8dad-addcee4fde3b.png)
![2019-10-21](https://user-images.githubusercontent.com/56784962/67170246-19f31e80-f3e3-11e9-9d33-222aad7ee466.png)

**Comment by Lisias** [comment]
TweakScale, as stated above, don't works on any KSP running on Unity 2019 for while.

Use it on KSP 1.7.3 or earlier (on the Archive, you will find TweakScale versions for almost every KSP ever released).

**Comment by Lisias** [comment]
Hummm… Chinese….

我正在使用Google翻译来与您交流。 抱歉，我不会说普通话或任何其他汉语方言。 我很抱歉

遵循以上帖子：

“如上所述，TweakScale暂时无法在Unity 2019上运行的任何KSP上运行。

在KSP 1.7.3或更早版本上使用它（在存档中，您几乎可以找到几乎所有已发布的KSP的TweakScale版本）。
Wǒ zhèngzài shǐyòng Google fānyì lái yǔ nín jiāoliú. Bàoqiàn, wǒ bù huì shuō pǔtōnghuà huò rènhé qítā hànyǔ fāngyán. Wǒ hěn bàoqiàn

**Comment by Lisias** [comment]
Hmm.. I don't know the difference between hanzi and kanji. I will try Japanese too.

Google翻訳を使用して、あなたとのコミュニケーションを図っています。 申し訳ありませんが、私は日本語を話せません。 謝罪

上記の投稿に従います：

「TweakScaleは、前述のとおり、しばらくUnity 2019で実行されているKSPでは動作しません。

KSP 1.7.3以前で使用します（アーカイブには、これまでにリリースされたほぼすべてのKSPのTweakScaleバージョンがあります）。
Gūguru hon'yaku o shiyō shite, anata to no komyunikēshon o hakatte imasu. Mōshiwakearimasenga, watashi wa nihongo o hanasemasen. Shazai jōki no tōkō ni shitagaimasu: `TweakScale wa, zenjutsu no tōri, shibaraku yuniti 2019 de jikkō sa rete
