### ISSUE TITLE
EngineFlare wrong position

### ISSUE THREAD

**Issue by zkx741481546** [net-lisias-ksp/TweakScale#84]
KSP1.7.3
TweakScale 2.4.3.10
RealPlume
...

It seems the position of Engine flare won't change after tweakscale engine

**Comment by Lisias** [comment]
Need more information. A screenshot of the problem would be nice too.

Could it be the same thing described on Issue #27 ?

**Comment by Lisias** [comment]
Closing as duplicate, as everything appears to pinpoint this is the same issue as #27
