### ISSUE TITLE
FATAL ERROR from TweakScale

### ISSUE THREAD

**Issue by Jiraiyah** [net-lisias-ksp/TweakScale#90]
Hi
Someone gave out an unofficial version of civilian population but now, i get the fatal error duplicate input, i know it means that some other mod (possibly) is trying to tweak the same part, how can i find what is going on there?

**Comment by Jiraiyah** [comment]
Found the problem but not sure why it's happening, I have this MM patch : 

@PART[*]: HAS[@MODULE[ModuleDockingNode]] :NEEDS[Konstruction] : FINAL
{
	%MODULE
	{
		name = ModuleWeldablePort
		portSnap = false
	}
}

When i add it to the folder I get the error

**Comment by Lisias** [comment]
Publish your KSP.log here, as well the place from where you downloaded the Civilian Population fork you are using. This will help me on diagnosing the problem.

**Comment by Jiraiyah** [comment]
It's not civilian population, I even tried a very light weighted, modded game with my own part mod (only three parts one sattlite box, one walls, and one battery), keeping the above MM patch, was still causing the issue, so, i think, if you add that patch to any modded game, it will crash ! even if konstruction is not installed !

**Comment by Jiraiyah** [comment]
Here is my mod : 

https://spacedock.info/mod/1649/JSat

and the ksp log : 

https://www.dropbox.com/s/v6cc8xmqc00j5mu/KSP.log?dl=0

**Comment by Jiraiyah** [comment]
[LOG 00:07:34.634] [TweakScale] WARNING: **FATAL** Found a showstopper problem on JSatWall (Jast Wall).
[LOG 00:07:34.634] [TweakScale] ERROR: **FATAL** Part JSatWall (Jast Wall) has a fatal problem due having duplicated properties - see issue [#34]( https://github.com/net-lisias-ksp/TweakScale/issues/34 ).
[LOG 00:07:34.641] [TweakScale] WARNING: **FATAL** Found a showstopper problem on rocketNoseCone (Protective Rocket Nose Cone Mk7).

**Comment by Jiraiyah** [comment]
@PART[JSatWall] : NEEDS[Scale,Scale_Redist] : FINAL
{
    %MODULE[TweakScale]
    {
        type = stack
        defaultScale = 2.5
    }
}

@PART[JSatFrame] : NEEDS[Scale,Scale_Redist] : FINAL
{
    %MODULE[TweakScale]
    {
        type = stack
        defaultScale = 2.5
    }
}

**Comment by Lisias** [comment]
Humm. Interesting. That should not had worked at all, the patch should be wrote like this:

```
@part[JSatWall]:NEEDS[TweakScale]:FOR[JSat]
{
	%MODULE[TweakScale]
	{
		type = stack
		defaultScale = 2.5
	}
}

@part[JSatFrame]:NEEDS[TweakScale]:FOR[JSat]
{
	%MODULE[TweakScale]
	{
		type = stack
		defaultScale = 2.5
	}
}
```

I just learnt the hard way on Forum that Module Manager doesn't likes spaces. :(

I usually would recommend to use % on the fieldnames, but since you own the thing, you are the one defining how it should behave, and so IMHO it's a best practice to use fieldnames without % in order to detect rogue patching on your add'on.

Since you are the owner of the thing, using :FOR is also an excellent idea. You don't need :FINAL, this thing is intended as a last measure to ensure things can work fine with legacy add'ons that doesn't knows what's :BEFORE or :AFTER, or to user defined patches that should be alwaus patched by last.

Since you are not patching something TweakScale is patching also, you don't need :AFTER[TweakScale] - and this is something that will really work only on TweakScale 2.4.4 anyway (to be released next month, I hope).

**Comment by Lisias** [comment]
Let me know if this works for you. If not, I will download your add'on, install on a test bed and so we will debug this thing together!

**Comment by Lisias** [comment]
I renamed the issue, as Civilian Population surely has no part on this problem.

**Comment by Jiraiyah** [comment]
Well first of all the patch was like that before, but i tweaked it lately, converted back, but it didn't solve the issue, the problem is, as soon as i put this patch in the folder, I get the fatal error :

@part[*]: HAS[@module[ModuleDockingNode]] :NEEDS[Konstruction] : FINAL
{
%MODULE
{
name = ModuleWeldablePort
portSnap = false
}
}

as much as i understand, the final here should not be a problem because i sort of, want it to happen at the end of everything to get the patch on every thing, also, i am using % on the module and specifically aiming docking port of any king to add rover dude's module on top of them. why is this causing the issue anyway?

**Comment by Lisias** [comment]
There're spaces between ":" and "HAS" , as well before ":NEEDS".

There's also spaces before and after ":" on "FINAL". AFAIK, MM is picky about spaces on the wrong places.

In a way or another, SpaceDock is back to business. I'm downloading your Add'On and giving this a shot now.

**Comment by Lisias** [comment]
I'm an idiot, by the way. Where I wrote "@part" on my previous posts, please read "@PART". :D

**Comment by Lisias** [comment]
And there's something weird happening. This is your Add'On listing from KSP.log:

```
Mod DLLs found:
Stock assembly: Assembly-CSharp v0.0.0.0
Scale_Redist v1.0.0.0 / v2.4.3.10
KSPModFileLocalizer v0.2.3.4
ModuleManager v4.1.2.0
ClickThroughBlocker v0.1.9.5 / v1.0.0.0
aaa_Toolbar v1.8.0.5
ToolbarControl v0.1.9.4 / v1.0.0.0
B9AnimationModules v1.6.0.0 / vv1.6.0
B9PartSwitch v2.12.1.0 / vv2.12.1
KSPe.Light.TweakScale v2.1.0.17
Scale v2.4.3.10

Folders and files in GameData:
000_ClickThroughBlocker
000_Toolbar
001_ToolbarControl
B9AnimationModules
B9PartSwitch
JSat
Stock folder: Squad

TweakScale
zzzz_JPatches
999_Scale_Redist.dll
KSPModFileLocalizer.dll
ModuleManager.4.1.2.dll
ModuleManager.ConfigCache
ModuleManager.ConfigSHA
ModuleManager.Physics
ModuleManager.TechTree
toolbar-settings.dat
```

No Konstruction. But you have B9PartSwitch. There're some combinations of third-parties with B9PartSwitch that TweakScale rejects, because they don't go very well together and TweakScale ends up taking the heat.  However, there's nothing more on your KSP.log that could trigger this issue, so I'm thinking something is fooling TweakScale's Sanity Checks.

**Comment by Lisias** [comment]
However, there's only #34 on your log, so it's surely a coincidence.

**Comment by Lisias** [comment]
I think I found it. It's completely unrelated to what you are complaining, it's a patch outside JSat playing havoc on your system:

```
[LOG 00:04:26.099] Applying update JSat/MM_TweakScalePatches/@PART[JSatWall] to JSat/Parts/SatWall.cfg/PART[JSatWall]
[LOG 00:04:27.476] Applying update zzzz_JPatches/USI_PATCHES/@PART[*]: to JSat/Parts/SatWall.cfg/PART[JSatWall]
```

The problems are on zzzz_JPatches.cfg . There's nothing else patching the affected parts. Look, this is another affected part:

```
[LOG 00:04:27.374] Applying update TweakScale/patches/Squad/Squad_Util/@PART[batteryPack] to Squad/Parts/Electrical/z-100Battery/z-100Battery.cfg/PART[batteryPack]
[LOG 00:04:27.487] Applying update zzzz_JPatches/USI_PATCHES/@PART[*]: to Squad/Parts/Electrical/z-100Battery/z-100Battery.cfg/PART[batteryPack]
```

And yet another one:

```
[LOG 00:04:27.340] Applying update TweakScale/patches/Squad/Squad_Tanks/@PART[mk3FuselageLF_25] to Squad/Parts/FuelTank/mk3Fuselage/LF_25.cfg/PART[mk3FuselageLF_25]
[LOG 00:04:27.500] Applying update zzzz_JPatches/USI_PATCHES/@PART[*]: to Squad/Parts/FuelTank/mk3Fuselage/LF_25.cfg/PART[mk3FuselageLF_25]
```

In all cases, the patches on zzzz_JPatches are the ones borking on you!

**Comment by Lisias** [comment]
Can you post zzzz_JPatches/USI_PATCHES.cfg for analysis? I'm pretty sure is something pretty stupid, as a misplace wirldcard or something.

These small glitches are the worst to catch!

**Comment by Jiraiyah** [comment]
the patch file is only and only the mm patch i sent to you above, i was trying to start patching for usi, that was the very first MM i wrote for it and i got stock so I stoped right there to find what is going on.
I'm almost a noob on modding so what you are saying about my mod is a bit out of my understanding :D can you please explain a little more?

DARM IT !!!

You were right about spaces, removing the spaces solved the issue. sorry all the trouble and time I took from you, on a second thought, is there a way for you to look for this special space cases in your code and at the same time, when you are warning the player about the crash you warn them about those spaces or will this be too much work programming wise?

**Comment by Lisias** [comment]
Welcome aboard! You are now, officially, an Add'On developer!! :D :D :D 

About the spaces problem... It's a Module Manager issue, and it's beyound TweakScale to handle it. When TweakScale finally has a chance to inspect the Gamedatabase, the 'source code' for the patch is long forgotten.

But that spaces thingy is something that, yeah, it would add value to the tool. I will check the MM thread to see if someone else is already working on this, or if there's something that prevents this to be implemented (it can happen).

(I have a personal fork for MM where I just fix things on my way, but I avoid to change features as a bad standard is better than no standard at all. :) )

Let's see what happens.
