### ISSUE TITLE
This mod is dead now.

### ISSUE THREAD

**Issue by kiwi1960** [net-lisias-ksp/TweakScale#97]
Yet another mod taken over by this guy who has no clue. Impossible innovations was a good mod till this guy took over, and this one will head the same way. He is a wannabe coder.

**Comment by Lisias** [comment]
This issue is plain harrasment. User was blocked and reported.

**Comment by Lisias** [comment]
And for anyone that read this, I'm far from being clueless. :)

https://forum.kerbalspaceprogram.com/index.php?/topic/192048-ksp-recall-0010-early-adopters-program-2020-0301/
